services:
  - type: web
    name: f1dashboard
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.x  # Consider using the latest patch version
    healthCheckPath: /health  # Optional, if you have a health check endpoint
