services:
  - type: web
    name: f1dashboard
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip wheel
      pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server --workers 3
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10  # Replace with the specific version you want to use
    healthCheckPath: /health  # Ensure this path exists or remove it
