<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jorge Borja">
<meta name="author" content="Jose Mercado">
<meta name="description" content="La Fórmula 1, también conocida como F1, representa la cúspide de las carreras internacionales de monoplazas de ruedas abiertas, bajo la supervisión de la Federación Internacional del Automóvil (FIA). Desde su primera temporada en 1950, el Campeonato Mundial de Pilotos, rebautizado como el Campeonato Mundial de Fórmula 1 de la FIA en 1981, ha destacado como una de las principales competiciones a nivel global. La palabra “fórmula” en su nombre alude al conjunto de reglas que guían a todos los participantes en cuanto a la construcción y funcionamiento de los vehículos.">

<title>F1 Dashboard - Campeonato Mundial de la Formula 1 (1950 - 2023)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./timeseries.html" rel="next">
<link href="./drivers.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

<script type="text/javascript">

window.PlotlyConfig = {MathJaxConfig: 'local'};

if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}

if (typeof require !== 'undefined') {

require.undef("plotly");

requirejs.config({

    paths: {

        'plotly': ['https://cdn.plot.ly/plotly-2.30.0.min']

    }

});

require(['plotly'], function(Plotly) {

    window._Plotly = Plotly;

});

}

</script>



<link rel="apple-touch-icon" sizes="180x180" href="icon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="32x32" href="icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="icon/favicon-16x16.png">
<link rel="manifest" href="icon/manifest.json">
<link rel="mask-icon" href="icon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./logisticbinary.html">Análisis Predictivos</a></li><li class="breadcrumb-item"><a href="./logisticbinary.html">Modelo de Regresión Logística Binaria</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="color: #e10600">F1</span> Dashboard</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Análisis Exploratorio de Datos (EDA)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./races.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de la tabla races</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./constructors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de la tabla constructors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./drivers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de la tabla drivers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Análisis Predictivos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logisticbinary.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Modelo de Regresión Logística Binaria</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./timeseries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelo de Serie de Tiempo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#definición" id="toc-definición" class="nav-link active" data-scroll-target="#definición">Definición</a></li>
  <li><a href="#planteamiento-del-problema" id="toc-planteamiento-del-problema" class="nav-link" data-scroll-target="#planteamiento-del-problema">Planteamiento del problema</a></li>
  <li><a href="#obtención-de-los-datos" id="toc-obtención-de-los-datos" class="nav-link" data-scroll-target="#obtención-de-los-datos">Obtención de los datos</a></li>
  <li><a href="#construcción-del-modelo-logístico" id="toc-construcción-del-modelo-logístico" class="nav-link" data-scroll-target="#construcción-del-modelo-logístico">Construcción del modelo logístico</a></li>
  <li><a href="#evaluación-del-modelo" id="toc-evaluación-del-modelo" class="nav-link" data-scroll-target="#evaluación-del-modelo">Evaluación del modelo</a></li>
  <li><a href="#visualización-de-los-resultados" id="toc-visualización-de-los-resultados" class="nav-link" data-scroll-target="#visualización-de-los-resultados">Visualización de los resultados</a>
  <ul class="collapse">
  <li><a href="#curva-roc" id="toc-curva-roc" class="nav-link" data-scroll-target="#curva-roc">Curva ROC</a></li>
  <li><a href="#matriz-de-confusión" id="toc-matriz-de-confusión" class="nav-link" data-scroll-target="#matriz-de-confusión">Matriz de confusión</a></li>
  </ul></li>
  <li><a href="#modelo-logístico" id="toc-modelo-logístico" class="nav-link" data-scroll-target="#modelo-logístico">Modelo Logístico</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./logisticbinary.html">Análisis Predictivos</a></li><li class="breadcrumb-item"><a href="./logisticbinary.html">Modelo de Regresión Logística Binaria</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Campeonato Mundial de la Formula 1 (1950 - 2023)</h1>
<p class="subtitle lead">Visualización Científica</p>
</div>

<div>
  <div class="description">
    <p>La Fórmula 1, también conocida como F1, representa la cúspide de las carreras internacionales de monoplazas de ruedas abiertas, bajo la supervisión de la Federación Internacional del Automóvil (FIA). Desde su primera temporada en 1950, el Campeonato Mundial de Pilotos, rebautizado como el Campeonato Mundial de Fórmula 1 de la FIA en 1981, ha destacado como una de las principales competiciones a nivel global. La palabra “fórmula” en su nombre alude al conjunto de reglas que guían a todos los participantes en cuanto a la construcción y funcionamiento de los vehículos.</p>
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autores/as</div>
  <div class="quarto-title-meta-heading">Afiliación</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://www.linkedin.com/in/jorgeborjas25/">Jorge Borja, Mag</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://uninorte.edu.co/">
            Universidad del Norte
            </a>
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://www.linkedin.com/in/jose-javier-mercado-reyes-246352214/">Jose Mercado, Mag</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="definición" class="level1">
<h1>Definición</h1>
<p>La regresión lineal es una herramienta de modelado ampliamente aplicable, pero no es apropiada cuando el modelo correcto debe ser no lineal en los parámetros. Tal es el caso cuando el punto final del estudio es una variable binaria. El modelo se vuelve no lineal porque lo que se está modelando es la probabilidad de que un caso experimente el evento de interés o que un caso esté en una categoría particular de la respuesta binaria <span class="citation" data-cites="DeMaris2013">(<a href="#ref-DeMaris2013" role="doc-biblioref">DeMaris y Selman 2013</a>)</span>.</p>
<p><span class="citation" data-cites="ibm_logistic_regression">(<a href="#ref-ibm_logistic_regression" role="doc-biblioref">IBM 2024</a>)</span> Este tipo de modelo estadístico (también conocido como modelo logit) se utiliza frecuentemente para clasificación y análisis predictivo. Dado que el resultado es una probabilidad, la variable dependiente está limitada entre 0 y 1. En la regresión logística, se aplica una transformación logit a las probabilidades, es decir, la probabilidad de éxito dividida por la probabilidad de fracaso. Esto también se conoce comúnmente como logaritmo de las probabilidades o logaritmo natural de las probabilidades, y esta función logística se representa mediante las siguientes fórmulas:</p>
<p><span class="math display">\[
    \text{Logit} (p_j) := \ln\left(\frac{p_j}{1-p_j}\right) =  \delta  \;+\;  \beta_1 \,x_{j1}  \;+\;\cdots \;+\; \beta_K \,x_{jK}.
\]</span></p>
<p>En esta ecuación de regresión logística, <span class="math inline">\(\text{Logit} (p_j)\)</span> es la variable <code>dependiente</code> o de respuesta, y <span class="math inline">\(x\)</span> es la variable <code>independiente</code>. El <code>parámetro beta</code>, o coeficiente, en este modelo comúnmente se estima mediante la <code>estimación de máxima verosimilitud</code> (MLE, por sus siglas en inglés). Este método prueba diferentes valores de beta a través de múltiples iteraciones para optimizar el mejor ajuste de los logaritmos de las probabilidades. Todas estas iteraciones producen la <code>función de verosimilitud logarítmica</code>, y la regresión logística busca maximizar esta función para encontrar la mejor estimación de los parámetros. Una vez que se encuentra el coeficiente óptimo (o coeficientes si hay más de una variable independiente), se pueden calcular las probabilidades condicionales para cada observación, tomarles el logaritmo y sumarlos para obtener una probabilidad predicha. Para la clasificación binaria, una probabilidad menor que 0.5 predecirá 0, mientras que una probabilidad mayor que 0.5 predecirá 1.</p>
<p><span class="citation" data-cites="llinas2012multinomial">(<a href="#ref-llinas2012multinomial" role="doc-biblioref">Llinás y Carreño 2012</a>)</span> Notemos que este modelo es construido suponiendo una matriz de diseño de la siguiente forma:</p>
<p><span class="math display">\[
    C = \left(
        \begin{array}{cccc}
            1          &amp; x_{11}    &amp;\cdots     &amp;x_{1K}\\
            1          &amp; x_{21}    &amp;\cdots     &amp;x_{2K}\\
            \vdots     &amp;\vdots     &amp;           &amp;\vdots\\
            1          &amp;x_{J1}     &amp;\cdots     &amp;x_{JK}\\
        \end{array}
    \right)
\]</span></p>
<p>donde el rango completo de esta matriz estará dado por: <span class="math inline">\(Rg(C) = 1 + K \leq J\)</span>, tal que <span class="math inline">\(J\)</span> representa el número de poblaciones existentens en los datos.</p>
<p>La ecuación denotada para <span class="math inline">\(\text{Logit} (p_j)\)</span> es conocido como el modelo logístico. Sin embargo, para hallarlo necesitamos conocer el valor de <span class="math inline">\(p_j\)</span>. Este valor representa la probabilidad (<code>riesgo</code>) de que se obtenga alguna de las respuestas de la variable dependiente. Entonces, la probabilidad</p>
<p><span class="math display">\[
    p_j = P\left(Y_j = 1 | x_{j1},\dots, x_{jK}\right),
\]</span></p>
<p>de obtener un éxito en la población <span class="math inline">\(j = 1, \dots, J\)</span>, dados los valores <span class="math inline">\(x_{j1},\dots, x_{jK}\)</span>, viene dada por:</p>
<p><span class="math display">\[
    p_j \;= \; \mbox{Logit}^{-1}(g_j) \;= \; \frac{e^{g_j}} {1 + e^{g_j}},
\]</span></p>
<p>donde <span class="math inline">\(g_j\)</span> está definido así:</p>
<p><span class="math display">\[
    g_j:=\delta \;+\; \beta_1\,x_{1j} \;+\;\cdots \;+\; \beta_K \,x_{Kj},
\]</span></p>
<p>con vector de parámetros <span class="math inline">\(\alpha = \left(\delta, \beta_1, \dots, \beta_K \right)^\top\)</span>. Ahora, para obtener el logaritmo de la función de verosimilitud del modelo logístico debemos tener en cuenta la siguiente ecuación:</p>
<p><span class="math display">\[
    \begin{align*}
        \cal L (p) &amp;= \sum_{j = 1}^J \left(\sum_{i = 1}^n \left[y_{ij} \ln (p_j) + (1 - y_{ij}) \ln (1 - p_j)\right]\right) \\
        &amp;=  \sum_{j = 1}^J \left[z_j \ln (p_j) + (n_j - z_j) \ln (1 - p_j)\right],
    \end{align*}
\]</span></p>
<p>tal que <span class="math inline">\(z_j\)</span> es una variable aleatoria binomial <span class="math inline">\(z_j \sim{\cal B} (n_j, p_j)\)</span> de las distintas poblaciones.</p>
<p>Ahora, reescribiendo esta ecuación en términos de <span class="math inline">\(\alpha\)</span> tenemos</p>
<p><span class="math display">\[
    \begin{align*}
        {\cal L} ({\alpha}) &amp;= \sum^{J}_{j = 1} \left[z_j \ln \left(\frac{p_j}{1 - p_j}\right) + n_j \ln(1 - p_j)\right] \\
        &amp;= \sum^{J}_{j = 1} z_j \, g_j \;-\; \sum^{J}_{j = 1} n_j \ln \left[1 + e^{g_j}\right].
    \end{align*}
\]</span></p>
</section>
<section id="planteamiento-del-problema" class="level1">
<h1>Planteamiento del problema</h1>
<p>En el ámbito del deporte del automovilismo, predecir el rendimiento de un equipo en una carrera es crucial para estrategias efectivas y toma de decisiones informadas. Se propone desarrollar un modelo logístico binario para determinar la probabilidad de que un equipo alcance la meta en una carrera. Este modelo se basará en varios atributos relacionados con el equipo, los pilotos y la carrera misma.</p>
<p><strong>Variables Independientes:</strong> 1. <strong>Posición Inicial en la Parrilla (grid):</strong> La posición en la que un equipo comienza la carrera puede influir significativamente en sus posibilidades de éxito. Se espera que equipos con posiciones de partida más adelantadas tengan una mayor probabilidad de llegar a la meta.</p>
<ol start="2" type="1">
<li><p><strong>Duración para Finalizar la Carrera (milliseconds):</strong> El tiempo necesario para que un equipo complete la carrera puede indicar tanto su rendimiento general como su capacidad para enfrentar desafíos y mantener la consistencia a lo largo de la competición.</p></li>
<li><p><strong>Velocidad más Alta Alcanzada en la Vuelta Más Rápida (fastestlapspeed):</strong> La velocidad máxima alcanzada por un equipo durante la carrera puede reflejar su habilidad para optimizar el rendimiento de su vehículo y aprovechar al máximo las oportunidades en la pista.</p></li>
<li><p><strong>ID del Equipo (constructorid):</strong> La identificación única del equipo puede capturar aspectos relacionados con su experiencia, recursos y estrategias de desarrollo técnico, los cuales pueden influir en su desempeño en la carrera.</p></li>
<li><p><strong>Edad de los Pilotos (age):</strong> La edad de los pilotos del equipo, calculada a partir de la fecha de la carrera y la fecha de nacimiento de los pilotos, podría tener implicaciones en términos de experiencia, habilidades físicas y capacidad para manejar la presión de la competición.</p></li>
<li><p><strong>Número de Paradas en los Boxes (pit_stop):</strong> El número de paradas en los boxes durante la carrera puede indicar la eficiencia en la gestión de neumáticos, combustible y ajustes de estrategia, lo cual influye directamente en el tiempo total de la carrera y, por ende, en la probabilidad de llegar a la meta.</p></li>
</ol>
<p><strong>Variable Dependiente:</strong> - <strong>Llegada a la Meta (finished_or_no):</strong> Esta variable binaria representará si el equipo logra o no alcanzar la meta al finalizar la carrera. Será el objetivo de nuestro modelo logístico, donde un valor de 1 indicará éxito (llegada a la meta) y un valor de 0 indicará fracaso (no llegar a la meta).</p>
<p>El objetivo principal será construir un modelo logístico que, utilizando estas variables independientes, pueda predecir la probabilidad de que un equipo alcance la meta en una carrera dada. Esto permitirá a los equipos tomar decisiones más informadas sobre estrategias de carrera y optimización de recursos para mejorar sus posibilidades de éxito en competiciones futuras.</p>
</section>
<section id="obtención-de-los-datos" class="level1">
<h1>Obtención de los datos</h1>
<p>Siguiendo el mismo enfoque utilizado en la sección anterior para llevar a cabo los análisis exploratorios, emplearemos una función para establecer la conexión con la base de datos.</p>
<p>Primero, importamos las bibliotecas necesarias:</p>
<div id="af16c939" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> psycopg2 <span class="im">as</span> psy</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> psycopg2 <span class="im">import</span> Error</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.graph_objects <span class="im">as</span> go</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación, creamos la función que facilita las conexiones:</p>
<div id="031d3ce0" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> connection_db() <span class="op">-&gt;</span> psy.extensions.connection:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        conn <span class="op">=</span> psy.<span class="ex">connect</span>(DATABASE_URL)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> conn</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">'Error while connecting to PostgreSQL'</span>, e)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es importante destacar que esta función utiliza una variable de entorno para almacenar los datos de conexión a la base de datos. En este caso, estamos utilizando <a href="https://neon.tech/">Neon</a>, que nos permite crear un servidor de bases de datos con <code>PostgreSQL</code>.</p>
<p>Como mencionamos previamente, las tablas y sus respectivas columnas que utilizaremos para el desarrollo de este modelo son las siguientes:</p>
<ul>
<li><strong>Results:</strong> points (determinará si finalizó la carrera o no), grid (posición inicial), milliseconds (duración de la carrera en milisegundos), fastestlapspeed (velocidad más alta alcanzada en la vuelta más rápida) y constructorid (identificador del equipo).</li>
<li><strong>Races:</strong> date (fecha en que se celebró la carrera).</li>
<li><strong>Drivers:</strong> dob (fecha de nacimiento del piloto).</li>
<li><strong>Pit_stops:</strong> stop (número de paradas en boxes).</li>
</ul>
<p>Luego, ejecutamos la consulta SQL para obtener los datos relevantes:</p>
<div id="8b931e3d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="st">                CASE</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHEN r.points &gt; 0 THEN 1</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="st">                    ELSE 0</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="st">                END AS finished_or_no,</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="st">                r.grid, </span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="st">                r.milliseconds / 60000.0 AS minutes, </span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="st">                r.fastestlapspeed, r.constructorid,</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="st">                (DATE_PART('year', ra.date) - DATE_PART('year', d.dob)) as age,</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="st">                MAX(p.stop) as pit_stop</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM results r</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN drivers d ON r.driverid = d.driverid</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN races ra ON r.raceid = ra.raceid</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN pit_stops p ON r.raceid = p.raceid</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="st">            GROUP BY finished_or_no, r.grid, r.milliseconds, r.fastestlapspeed, r.constructorid, age;</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    records_data[<span class="st">'fastestlapspeed'</span>] <span class="op">=</span> pd.to_numeric(records_data[<span class="st">'fastestlapspeed'</span>])</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    records_data[<span class="st">'grid'</span>] <span class="op">=</span> records_data[<span class="st">'grid'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    records_data[<span class="st">'minutes'</span>] <span class="op">=</span> pd.to_numeric(records_data[<span class="st">'minutes'</span>])</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    display(records_data)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">finished_or_no</th>
<th data-quarto-table-cell-role="th">grid</th>
<th data-quarto-table-cell-role="th">minutes</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">constructorid</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">pit_stop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>20</td>
<td>74.375950</td>
<td>238.300</td>
<td>37</td>
<td>39.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0</td>
<td>17</td>
<td>78.781533</td>
<td>225.354</td>
<td>6</td>
<td>29.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0</td>
<td>5</td>
<td>106.310617</td>
<td>190.672</td>
<td>1</td>
<td>23.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0</td>
<td>0</td>
<td>68.550567</td>
<td>211.124</td>
<td>46</td>
<td>33.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0</td>
<td>14</td>
<td>95.686550</td>
<td>193.481</td>
<td>51</td>
<td>40.0</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25592</td>
<td>0</td>
<td>13</td>
<td>100.605233</td>
<td>206.567</td>
<td>17</td>
<td>30.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25593</td>
<td>1</td>
<td>11</td>
<td>113.479283</td>
<td>192.484</td>
<td>1</td>
<td>30.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25594</td>
<td>0</td>
<td>6</td>
<td>68.660150</td>
<td>243.718</td>
<td>4</td>
<td>24.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25595</td>
<td>1</td>
<td>1</td>
<td>122.271767</td>
<td>175.786</td>
<td>6</td>
<td>45.0</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25596</td>
<td>0</td>
<td>12</td>
<td>115.799983</td>
<td>181.054</td>
<td>32</td>
<td>31.0</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>25597 rows × 7 columns</p>
</div>
</div>
</div>
</div>
<p>Con este procedimiento, hemos obtenido los datos necesarios para nuestro análisis y modelado subsiguiente.</p>
</section>
<section id="construcción-del-modelo-logístico" class="level1">
<h1>Construcción del modelo logístico</h1>
<p>Después de obtener los datos, procedemos a la construcción de nuestro modelo de regresión logística para una variable respuesta tipo binaria. Teniendo en cuenta la definición anterior, podemos establecer que nuestro modelo <span class="math inline">\(g_j\)</span> estará compuesto por las siguientes variables:</p>
<p><span class="math display">\[
    \begin{align*}
        g_j = &amp;\delta + \beta_1 \text{grid} + \beta_2 \text{age} + \beta_3 \text{minutes} \\
        &amp;+ \beta_4 \text{fastestlapspeed} + \beta_5 \text{constructorid} + \beta_6 \text{pitstop}
    \end{align*}
\]</span></p>
<p>Para construir nuestro modelo en Python, emplearemos la biblioteca <code>statsmodels</code>. Sin embargo, es necesario separar inicialmente nuestro conjunto de datos en conjuntos de entrenamiento y prueba. Esto se realiza de la siguiente manera:</p>
<div id="60275d22" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> records_data.iloc[:, <span class="dv">1</span>:]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> records_data.iloc[:, <span class="dv">0</span>:<span class="dv">1</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, train_size<span class="op">=</span><span class="fl">0.7</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>train_data <span class="op">=</span> pd.concat([y_train, X_train], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> pd.concat([y_test, X_test], axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación, planteamos nuestro modelo utilizando las variables de interés:</p>
<div id="eadbd6c3" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> sm</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>log_reg <span class="op">=</span> sm.logit(<span class="st">'finished_or_no ~ grid + age + minutes + constructorid + pit_stop + fastestlapspeed'</span>, data <span class="op">=</span> train_data).fit()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.438082
         Iterations 7</code></pre>
</div>
</div>
<div id="f565bde4" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>                           Logit Regression Results                           
==============================================================================
Dep. Variable:         finished_or_no   No. Observations:                17917
Model:                          Logit   Df Residuals:                    17910
Method:                           MLE   Df Model:                            6
Date:                Wed, 24 Apr 2024   Pseudo R-squ.:                  0.2908
Time:                        19:35:45   Log-Likelihood:                -7849.1
converged:                       True   LL-Null:                       -11068.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         -30.2711      0.895    -33.825      0.000     -32.025     -28.517
grid               -0.2172      0.004    -54.823      0.000      -0.225      -0.209
age                -0.0030      0.004     -0.763      0.446      -0.011       0.005
minutes             0.1308      0.003     39.267      0.000       0.124       0.137
constructorid      -0.0057      0.000    -15.823      0.000      -0.006      -0.005
pit_stop            0.3959      0.021     19.235      0.000       0.356       0.436
fastestlapspeed     0.0901      0.003     31.568      0.000       0.085       0.096
===================================================================================</code></pre>
</div>
</div>
<p>Los coeficientes del modelo indican cómo cada variable predictora afecta la probabilidad de que un corredor de carreras finalice la carrera, de ello podemos afirmar lo siguiente: un <code>intercepto</code> negativo grande sugiere una baja probabilidad inicial de no finalizar la carrera. Una <code>posición de salida</code> más atrás en la parrilla y ser un <code>equipo</code> nuevo disminuyen la probabilidad de finalizar la carrera, mientras que un <code>tiempo de carrera</code> más largo, realizar un <code>pit stop</code> durante la carrera y alcanzar una <code>velocidad</code> alta en la vuelta más rápida aumentan esta probabilidad. La <code>edad del corredor</code> no parece tener un efecto significativo en la probabilidad de finalizar la carrera, como lo sugiere el intervalo de confianza que incluye cero para el coeficiente correspondiente. Todos los demás coeficientes son significativos, como lo indican los intervalos de confianza que no incluyen cero.</p>
<p>A continuación, procedemos a remover la variable <code>age</code> del modelo, ya que no es significativa, y observamos los resultados del nuevo modelo:</p>
<div id="65481d86" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> sm</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>log_reg_2 <span class="op">=</span> sm.logit(<span class="st">'finished_or_no ~ grid + minutes + constructorid + pit_stop + fastestlapspeed'</span>, data <span class="op">=</span> train_data).fit()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.438099
         Iterations 7</code></pre>
</div>
</div>
<div id="715a97f0" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>                           Logit Regression Results                           
==============================================================================
Dep. Variable:         finished_or_no   No. Observations:                17917
Model:                          Logit   Df Residuals:                    17911
Method:                           MLE   Df Model:                            5
Date:                Wed, 24 Apr 2024   Pseudo R-squ.:                  0.2908
Time:                        19:35:45   Log-Likelihood:                -7849.4
converged:                       True   LL-Null:                       -11068.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         -30.3484      0.889    -34.130      0.000     -32.091     -28.606
grid               -0.2169      0.004    -54.988      0.000      -0.225      -0.209
minutes             0.1308      0.003     39.273      0.000       0.124       0.137
constructorid      -0.0057      0.000    -16.060      0.000      -0.006      -0.005
pit_stop            0.3981      0.020     19.543      0.000       0.358       0.438
fastestlapspeed     0.0901      0.003     31.568      0.000       0.084       0.096
===================================================================================</code></pre>
</div>
</div>
<p>Es notable que la eliminación de la variable <code>age</code> no afectó negativamente la capacidad predictiva del modelo, lo que sugiere que la edad de los corredores puede no ser un factor determinante en su habilidad para finalizar una carrera. Sin embargo, es importante considerar que la relevancia de esta variable podría variar en función de otros factores contextuales o características específicas de la muestra de datos utilizada. Por otro lado, los resultados obtenidos son similares a los previamente concluidos, por lo que podemos proceder a analizar las métricas del modelo.</p>
</section>
<section id="evaluación-del-modelo" class="level1">
<h1>Evaluación del modelo</h1>
<p>En esta sección, nos centraremos en evaluar el desempeño de nuestro modelo de regresión logística utilizando diversas métricas de evaluación. Estas métricas son fundamentales para comprender cómo se comporta nuestro modelo en términos de su capacidad para predecir correctamente la variable de interés, en este caso, la probabilidad de finalizar una carrera.</p>
<p>Entre las métricas que utilizaremos se encuentran: <code>precision</code>, <code>recall</code>, <code>f1-score</code> y el área bajo la curva ROC (<code>AUC</code>). Cada una de estas métricas proporciona una perspectiva única sobre el rendimiento del modelo y nos ayudará a determinar su efectividad en la clasificación de los resultados.</p>
<ul>
<li><strong>Precision:</strong> mide cuántas de las muestras predichas como positivas son realmente positivas. Es decir, identifica qué proporción de identificaciones positivas son correctas.</li>
</ul>
<p><span class="math display">\[
    \text{precision} = \frac{TP}{TP + FP},
\]</span></p>
<p>donde <span class="math inline">\(TP\)</span> representa los verdaderos positivos y <span class="math inline">\(FP\)</span> los falsos positivos. Esta métrica se utiliza como métrica de rendimiento cuando el objetivo es <code>limitar el número de falsos positivos</code>.</p>
<ul>
<li><strong>Recall:</strong> mide cuántas de las muestras de la clase positiva son realmente predichas positivas. Es decir, nos muestra la proporción de instancias positivas que fueron correctamente identificadas por el modelo entre todas las instancias que realmente son positivas.</li>
</ul>
<p><span class="math display">\[
    \text{recall} = \frac{TP}{TP + FN}
\]</span></p>
<p>donde <span class="math inline">\(FN\)</span> son los falsos negativos. Este métrica se utiliza como métrica de rendimiento cuando el objetivo es <code>limitar el número de falsos negativos</code>.</p>
<p>Existe un equilibrio entre la optimización del <code>recall</code> y el <code>precision</code>. Se puede obtener de forma sencilla, una recuperación perfecta si se predice que todas las muestras pertenecen a la clase positiva. Si se predice que todas las muestras pertenecen a la clase positiva, no habrá falsos negativos ni verdaderos negativos. Sin embargo, predecir todas las muestras como positivas, dará lugar a muchos falsos positivos y, por lo tanto, su <code>precision</code> será muy baja. Por otro lado, si se encuentra un modelo que predice sólo el punto de datos del que se está más seguro como positivo y el resto como negativo, entonces <code>precision</code> será perfecto (suponiendo que este punto de datos sea de hecho positivo), pero el <code>recall</code> será muy malo <span class="citation" data-cites="lihkir_model_evaluation">(<a href="#ref-lihkir_model_evaluation" role="doc-biblioref">Rubio 2024</a>)</span>.</p>
<p>Por lo tanto, aunque <code>precision</code> y <code>recall</code> sean medidas muy importantes, si sólo se tiene en cuenta una de ellas no se obtiene una visión completa. Una forma de resumirlas es usando el <code>f-score</code>, que es la <code>media armónica</code> entre precision y recall:</p>
<p><span class="math display">\[
    \text{F} = 2 \cdot \frac{\text{precision} \cdot \text{recall}}{\text{precision} + \text{recall}}.
\]</span></p>
<p>Esta variante concreta también se conoce como <span class="math inline">\(f_1\)</span>-score. Finalmente, el área bajo la curva <code>ROC</code> proporciona una evaluación del rendimiento global del modelo, considerando todas las posibles tasas de verdaderos positivos frente a falsos positivos.</p>
<p>Veamos entonces cuáles son los resultados para las métricas mencionadas en nuestros modelos</p>
<div id="daa6b88e" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> precision_score, recall_score, f1_score, roc_auc_score</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> log_reg.predict(X_test)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> np.where(y_pred <span class="op">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>precision <span class="op">=</span> precision_score(y_test, y_pred)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>recall <span class="op">=</span> recall_score(y_test, y_pred)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> f1_score(y_test, y_pred)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>auc <span class="op">=</span> roc_auc_score(y_test, y_pred)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>y_pred2 <span class="op">=</span> log_reg_2.predict(X_test)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>y_pred2_a <span class="op">=</span> np.where(y_pred2 <span class="op">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>precision2 <span class="op">=</span> precision_score(y_test, y_pred2_a)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>recall2 <span class="op">=</span> recall_score(y_test, y_pred2_a)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>f1_2 <span class="op">=</span> f1_score(y_test, y_pred2_a)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>auc2 <span class="op">=</span> roc_auc_score(y_test, y_pred2_a)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="b50eb303" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="68">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Precision</th>
<th data-quarto-table-cell-role="th">Recall</th>
<th data-quarto-table-cell-role="th">F1-score</th>
<th data-quarto-table-cell-role="th">AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Logit 1</td>
<td>0.764969</td>
<td>0.593831</td>
<td>0.668623</td>
<td>0.757868</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Logit 2</td>
<td>0.765886</td>
<td>0.596872</td>
<td>0.670898</td>
<td>0.759388</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Las métricas de evaluación muestran que el modelo <code>Logit 2</code> presenta una mejora marginal en comparación con <code>Logit 1</code> en la clasificación de los resultados de finalización de la carrera. Ambos modelos tienen una precisión, recall y AUC similares, pero el <code>Logit 2</code> muestra una leve mejora en el F1-score, lo que sugiere un mejor equilibrio entre precisión y recall. En resumen, el <code>Logit 2</code> muestra un rendimiento ligeramente superior en la clasificación de los resultados en comparación con el <code>Logit 1</code>.</p>
</section>
<section id="visualización-de-los-resultados" class="level1">
<h1>Visualización de los resultados</h1>
<section id="curva-roc" class="level2">
<h2 class="anchored" data-anchor-id="curva-roc">Curva ROC</h2>
<p>Antes de realizar el gráfico de la curva ROC debemos ver dos gráficos que nos darán contexto al mecánismo de los umbrales detrás de esta curva.</p>
<div id="149adcf3" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_curve</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>fpr, tpr, thresholds <span class="op">=</span> roc_curve(y_test, y_pred2)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>y_test_g <span class="op">=</span> y_test[<span class="st">'finished_or_no'</span>].values</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>fig_hist <span class="op">=</span> px.histogram(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>y_pred2, color<span class="op">=</span>y_test_g, nbins<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">'True Labels'</span>, x<span class="op">=</span><span class="st">'Score'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>fig_hist.update_layout(</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span>{<span class="st">'b'</span>: <span class="dv">0</span>, <span class="st">'r'</span>: <span class="dv">30</span>, <span class="st">'l'</span>: <span class="dv">30</span>, <span class="st">'t'</span>: <span class="dv">0</span>},</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    xaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    plot_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    paper_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    font_color<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    hoverlabel<span class="op">=</span><span class="bu">dict</span>(</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>        bgcolor<span class="op">=</span><span class="st">"#111"</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>fig_hist.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<iframe src="roc_logit_binary_g1.html" width="730" height="520" title="ROC Logit Binary Graph 1">
</iframe>
<p>En el histograma, observamos que la puntuación se distribuye de tal forma que la mayoría de las etiquetas positivas y negativas se sitúan cerca de 0, y las que más valores se reunen en 1 serían las negativas. Cuando fijamos un umbral en la puntuación, todos los bines a su izquierda se clasificarán como 0, y todo a la derecha serán 1. Obviamente, hay algunos valores atípicos, como las muestras negativas a las que nuestro modelo dio una puntuación alta, y las muestras positivas con una puntuación baja. Si fijamos un umbral justo en el medio, esos valores atípicos se convertirán respectivamente en falsos positivos y falsos negativos.</p>
<p>Evaluemos entonces el rendimiento del modelo con diferentes umbrales</p>
<div id="307d3506" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'False Positive Rate'</span>: fpr,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'True Positive Rate'</span>: tpr</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>thresholds)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>df.index.name <span class="op">=</span> <span class="st">"Thresholds"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>df.columns.name <span class="op">=</span> <span class="st">"Rate"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>fig_thresh <span class="op">=</span> px.line(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    df, title<span class="op">=</span><span class="st">'TPR y FPR en cada umbral'</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    width<span class="op">=</span><span class="dv">700</span>, height<span class="op">=</span><span class="dv">500</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>fig_thresh.update_yaxes(scaleanchor<span class="op">=</span><span class="st">"x"</span>, scaleratio<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>fig_thresh.update_xaxes(<span class="bu">range</span><span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1</span>], constrain<span class="op">=</span><span class="st">'domain'</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>fig_thresh.update_layout(</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span>{<span class="st">'b'</span>: <span class="dv">0</span>, <span class="st">'r'</span>: <span class="dv">30</span>, <span class="st">'l'</span>: <span class="dv">30</span>, <span class="st">'t'</span>: <span class="dv">50</span>},</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    xaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    plot_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>    paper_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    font_color<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>    hoverlabel<span class="op">=</span><span class="bu">dict</span>(</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>        bgcolor<span class="op">=</span><span class="st">"#111"</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>fig_thresh.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<iframe src="roc_logit_binary_g2.html" width="730" height="520" title="ROC Logit Binary Graph 2">
</iframe>
<p>A medida que ajustamos los umbrales, el número de positivos aumentará o disminuirá, y al mismo tiempo también cambiará el número de verdaderos positivos; esto se muestra en el segundo gráfico. Como se puede ver, el modelo parece funcionar bastante bien, porque la tasa de verdaderos positivos disminuye lentamente, mientras que la tasa de falsos positivos disminuye bruscamente a medida que aumentamos el umbral. Cada una de esas dos líneas representa una dimensión de la curva ROC.</p>
<div id="b2bd2f98" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fig_roc <span class="op">=</span> px.area(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>fpr, y<span class="op">=</span>tpr,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="ss">f'Curva de ROC'</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span><span class="bu">dict</span>(x<span class="op">=</span><span class="st">'False Positive Rate'</span>, y<span class="op">=</span><span class="st">'True Positive Rate'</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    width<span class="op">=</span><span class="dv">700</span>, height<span class="op">=</span><span class="dv">500</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>fig_roc.add_shape(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">type</span><span class="op">=</span><span class="st">'line'</span>, line<span class="op">=</span><span class="bu">dict</span>(dash<span class="op">=</span><span class="st">'dash'</span>, color<span class="op">=</span><span class="st">'white'</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span><span class="dv">0</span>, x1<span class="op">=</span><span class="dv">1</span>, y0<span class="op">=</span><span class="dv">0</span>, y1<span class="op">=</span><span class="dv">1</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>fig_roc.add_annotation(</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    xref <span class="op">=</span> <span class="st">'paper'</span>, yref <span class="op">=</span> <span class="st">'paper'</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="fl">.95</span>, y <span class="op">=</span> <span class="fl">.05</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> <span class="ss">f'AUC: </span><span class="sc">{</span>auc2<span class="sc">:.4f}</span><span class="ss">'</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    showarrow <span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    bordercolor <span class="op">=</span> <span class="st">'black'</span>,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    borderwidth <span class="op">=</span> <span class="fl">.5</span>,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    bgcolor <span class="op">=</span> <span class="st">'#e10600'</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>fig_roc.update_yaxes(scaleanchor<span class="op">=</span><span class="st">"x"</span>, scaleratio<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>fig_roc.update_xaxes(constrain<span class="op">=</span><span class="st">'domain'</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>fig_roc.update_layout(</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span>{<span class="st">'b'</span>: <span class="dv">0</span>, <span class="st">'r'</span>: <span class="dv">30</span>, <span class="st">'l'</span>: <span class="dv">30</span>, <span class="st">'t'</span>: <span class="dv">50</span>},</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    xaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    plot_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>    paper_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    font_color<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    hoverlabel<span class="op">=</span><span class="bu">dict</span>(</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>        bgcolor<span class="op">=</span><span class="st">"#111"</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>fig_roc.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<iframe src="roc_logit_binary.html" width="730" height="520" title="ROC Logit Binary Graph">
</iframe>
<p>Notemos que esta curva ROC se parece a la curva de TPR del gráfico anterior. Esto se debe a que son la misma curva, salvo que el eje x consiste en valores crecientes de FPR en lugar de umbral, razón por la cual la línea está invertida y distorsionada. También se puede observar el área bajo la curva ROC (ROC AUC), que es bastante alta, lo que concuerda con nuestra interpretación de los gráficos anteriores.</p>
</section>
<section id="matriz-de-confusión" class="level2">
<h2 class="anchored" data-anchor-id="matriz-de-confusión">Matriz de confusión</h2>
<p>Otra forma de visualizar los aciertos en las predicciones de los modelos es mediante una matriz de confusión. En ella podremos observar los valores <span class="math inline">\(TP\)</span>, <span class="math inline">\(FP\)</span>, <span class="math inline">\(TN\)</span> y <span class="math inline">\(FN\)</span> predichos por el modelo y determinar qué tanto es el acierto.</p>
<div id="4efe0ecb" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.figure_factory <span class="im">as</span> ff</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>conf_matrix_log_reg <span class="op">=</span> confusion_matrix(y_test, y_pred2_a)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'No Finalizado'</span>, <span class="st">'Finalizado'</span>]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fig_cm <span class="op">=</span> ff.create_annotated_heatmap(conf_matrix_log_reg, x<span class="op">=</span>labels, y<span class="op">=</span>labels, colorscale<span class="op">=</span>[[<span class="dv">0</span>, <span class="st">'#FFFFFF'</span>], [<span class="dv">1</span>, <span class="st">'#e10600'</span>]])</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>fig_cm.update_layout(title<span class="op">=</span><span class="st">'Matriz de Confusión para Logit 2'</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>fig_cm.update_layout(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span>{<span class="st">'b'</span>: <span class="dv">0</span>, <span class="st">'r'</span>: <span class="dv">30</span>, <span class="st">'l'</span>: <span class="dv">30</span>, <span class="st">'t'</span>: <span class="dv">50</span>},</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    xaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span>{<span class="st">'gridcolor'</span>: <span class="st">'#111'</span>, <span class="st">'tickfont'</span>: {<span class="st">'color'</span>: <span class="st">'white'</span>}},</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    plot_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    paper_bgcolor<span class="op">=</span><span class="st">'rgba(0, 0, 0, 0.0)'</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    font_color<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    hoverlabel<span class="op">=</span><span class="bu">dict</span>(</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>        bgcolor<span class="op">=</span><span class="st">"#111"</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>fig_cm.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<iframe src="cm_logit_binary.html" width="730" height="520" title="Confusion Matrix Logit Binary Graph">
</iframe>
</section>
</section>
<section id="modelo-logístico" class="level1">
<h1>Modelo Logístico</h1>
<p>Luego de realizar la evaluación del modelo mediante las distinas métricas podemos determinar que el segundo modelo logístico obtenido se ajusta bien a los resultados esperados. Podemos notar un buen ajuste mediante la <strong>curva de ROC</strong> y también tenemos un buen valor para el <span class="math inline">\(f_1\)</span>-score la cual nos permite contemplar que hay una cantidad poco significativa de <span class="math inline">\(FP\)</span> y <span class="math inline">\(FN\)</span>. El modelo logístico entonces estaría dado de la siguiente forma:</p>
<p><span class="math display">\[
    \begin{align*}
    \hat{g_j} = &amp;- 30.3484 - 0.2169 \text{grid}_j + 0.1308 \text{minutes}_j - 0.0057 \text{constructorid}_j \\
        &amp;+ 0.3981 \text{pitstop}_j + 0.0901 \text{fastestlapspeed}_j
    \end{align*}
\]</span></p>
<p>donde <span class="math inline">\(j\)</span> será la población que se querrá predecir.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-DeMaris2013" class="csl-entry" role="listitem">
DeMaris, Alfred, y Steven H. Selman. 2013. <span>«Logistic Regression»</span>. En <em>Converting Data into Evidence: A Statistics Primer for the Medical Practitioner</em>, 115-36. New York, NY: Springer New York. <a href="https://doi.org/10.1007/978-1-4614-7792-1_7">https://doi.org/10.1007/978-1-4614-7792-1_7</a>.
</div>
<div id="ref-ibm_logistic_regression" class="csl-entry" role="listitem">
IBM. 2024. <span>«Logistic Regression»</span>. 2024. <a href="https://www.ibm.com/topics/logistic-regression">https://www.ibm.com/topics/logistic-regression</a>.
</div>
<div id="ref-llinas2012multinomial" class="csl-entry" role="listitem">
Llinás, Humberto, y Carlos Carreño. 2012. <span>«The Multinomial Logistic Model for the Case in which the Response Variable Can Assume One of Three Levels and Related Models»</span>. <em>Revista Colombiana de Estad<span>ı́</span>stica</em> 35 (1): 131-38.
</div>
<div id="ref-lihkir_model_evaluation" class="csl-entry" role="listitem">
Rubio, Lihki. 2024. <span>«Métricas de evaluación y scoring»</span>. 2024. <a href="https://lihkir.github.io/MachineLearningUninorte/model_evaluation.html#metricas-de-evaluacion-y-scoring">https://lihkir.github.io/MachineLearningUninorte/model_evaluation.html#metricas-de-evaluacion-y-scoring</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./drivers.html" class="pagination-link" aria-label="Análisis de la tabla drivers">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Análisis de la tabla drivers</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./timeseries.html" class="pagination-link" aria-label="Modelo de Serie de Tiempo">
        <span class="nav-page-text">Modelo de Serie de Tiempo</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>