<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jorge Borja">
<meta name="author" content="Jose Mercado">
<meta name="description" content="La Fórmula 1, también conocida como F1, representa la cúspide de las carreras internacionales de monoplazas de ruedas abiertas, bajo la supervisión de la Federación Internacional del Automóvil (FIA). Desde su primera temporada en 1950, el Campeonato Mundial de Pilotos, rebautizado como el Campeonato Mundial de Fórmula 1 de la FIA en 1981, ha destacado como una de las principales competiciones a nivel global. La palabra “fórmula” en su nombre alude al conjunto de reglas que guían a todos los participantes en cuanto a la construcción y funcionamiento de los vehículos.">

<title>F1 Dashboard - Campeonato Mundial de la Formula 1 (1950 - 2023)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./drivers.html" rel="next">
<link href="./races.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

<link rel="apple-touch-icon" sizes="180x180" href="icon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="32x32" href="icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="icon/favicon-16x16.png">
<link rel="manifest" href="icon/manifest.json">
<link rel="mask-icon" href="icon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./races.html">Análisis Exploratorio de Datos (EDA)</a></li><li class="breadcrumb-item"><a href="./constructors.html">Análisis de la tabla constructors</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="color: #e10600">F1</span> Dashboard</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Análisis Exploratorio de Datos (EDA)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./races.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de la tabla races</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./constructors.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Análisis de la tabla constructors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./drivers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de la tabla drivers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#qué-haremos" id="toc-qué-haremos" class="nav-link active" data-scroll-target="#qué-haremos">¿Qué haremos?</a></li>
  <li><a href="#librerías" id="toc-librerías" class="nav-link" data-scroll-target="#librerías">Librerías</a></li>
  <li><a href="#obtención-de-los-datos" id="toc-obtención-de-los-datos" class="nav-link" data-scroll-target="#obtención-de-los-datos">Obtención de los datos</a>
  <ul class="collapse">
  <li><a href="#tabla-constructors" id="toc-tabla-constructors" class="nav-link" data-scroll-target="#tabla-constructors">Tabla constructors</a></li>
  <li><a href="#tabla-circuits" id="toc-tabla-circuits" class="nav-link" data-scroll-target="#tabla-circuits">Tabla circuits</a></li>
  <li><a href="#tabla-results" id="toc-tabla-results" class="nav-link" data-scroll-target="#tabla-results">Tabla results</a></li>
  <li><a href="#tabla-pit-stops" id="toc-tabla-pit-stops" class="nav-link" data-scroll-target="#tabla-pit-stops">Tabla pit stops</a></li>
  <li><a href="#tabla-final" id="toc-tabla-final" class="nav-link" data-scroll-target="#tabla-final">Tabla final</a></li>
  </ul></li>
  <li><a href="#análisis-exploratorio-de-datos" id="toc-análisis-exploratorio-de-datos" class="nav-link" data-scroll-target="#análisis-exploratorio-de-datos">Análisis exploratorio de datos</a>
  <ul class="collapse">
  <li><a href="#conociendo-los-datos" id="toc-conociendo-los-datos" class="nav-link" data-scroll-target="#conociendo-los-datos">Conociendo los datos</a>
  <ul class="collapse">
  <li><a href="#tipos-de-datos" id="toc-tipos-de-datos" class="nav-link" data-scroll-target="#tipos-de-datos">Tipos de datos</a></li>
  <li><a href="#dimensiones-de-los-registros" id="toc-dimensiones-de-los-registros" class="nav-link" data-scroll-target="#dimensiones-de-los-registros">Dimensiones de los registros</a></li>
  <li><a href="#datos-faltantes" id="toc-datos-faltantes" class="nav-link" data-scroll-target="#datos-faltantes">Datos faltantes</a></li>
  </ul></li>
  <li><a href="#exploración-de-los-datos" id="toc-exploración-de-los-datos" class="nav-link" data-scroll-target="#exploración-de-los-datos">Exploración de los datos</a>
  <ul class="collapse">
  <li><a href="#medidas-de-tendencia-central" id="toc-medidas-de-tendencia-central" class="nav-link" data-scroll-target="#medidas-de-tendencia-central">Medidas de tendencia central</a></li>
  <li><a href="#limpieza-de-los-datos" id="toc-limpieza-de-los-datos" class="nav-link" data-scroll-target="#limpieza-de-los-datos">Limpieza de los datos</a></li>
  </ul></li>
  <li><a href="#visualización" id="toc-visualización" class="nav-link" data-scroll-target="#visualización">Visualización</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-correlación" id="toc-gráfico-de-correlación" class="nav-link" data-scroll-target="#gráfico-de-correlación">Gráfico de correlación</a></li>
  <li><a href="#gráfico-de-dispersión" id="toc-gráfico-de-dispersión" class="nav-link" data-scroll-target="#gráfico-de-dispersión">Gráfico de dispersión</a></li>
  <li><a href="#distribución-de-carreras" id="toc-distribución-de-carreras" class="nav-link" data-scroll-target="#distribución-de-carreras">Distribución de carreras</a></li>
  <li><a href="#distribución-de-costructores-por-nacionalidad" id="toc-distribución-de-costructores-por-nacionalidad" class="nav-link" data-scroll-target="#distribución-de-costructores-por-nacionalidad">Distribución de costructores por nacionalidad</a></li>
  <li><a href="#top-5-equipos-más-ganadores" id="toc-top-5-equipos-más-ganadores" class="nav-link" data-scroll-target="#top-5-equipos-más-ganadores">Top 5 equipos más ganadores</a></li>
  <li><a href="#evolución-de-la-velocidad" id="toc-evolución-de-la-velocidad" class="nav-link" data-scroll-target="#evolución-de-la-velocidad">Evolución de la velocidad</a></li>
  <li><a href="#evolución-de-la-velocidad-máxima-alcanzada-por-equipo" id="toc-evolución-de-la-velocidad-máxima-alcanzada-por-equipo" class="nav-link" data-scroll-target="#evolución-de-la-velocidad-máxima-alcanzada-por-equipo">Evolución de la velocidad máxima alcanzada por equipo</a></li>
  <li><a href="#evolución-de-las-paradas-en-boxes" id="toc-evolución-de-las-paradas-en-boxes" class="nav-link" data-scroll-target="#evolución-de-las-paradas-en-boxes">Evolución de las paradas en boxes</a></li>
  <li><a href="#evolución-de-las-paradas-en-boxes-por-equipo" id="toc-evolución-de-las-paradas-en-boxes-por-equipo" class="nav-link" data-scroll-target="#evolución-de-las-paradas-en-boxes-por-equipo">Evolución de las paradas en boxes por equipo</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./races.html">Análisis Exploratorio de Datos (EDA)</a></li><li class="breadcrumb-item"><a href="./constructors.html">Análisis de la tabla constructors</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Campeonato Mundial de la Formula 1 (1950 - 2023)</h1>
<p class="subtitle lead">Visualización Científica</p>
</div>

<div>
  <div class="description">
    <p>La Fórmula 1, también conocida como F1, representa la cúspide de las carreras internacionales de monoplazas de ruedas abiertas, bajo la supervisión de la Federación Internacional del Automóvil (FIA). Desde su primera temporada en 1950, el Campeonato Mundial de Pilotos, rebautizado como el Campeonato Mundial de Fórmula 1 de la FIA en 1981, ha destacado como una de las principales competiciones a nivel global. La palabra “fórmula” en su nombre alude al conjunto de reglas que guían a todos los participantes en cuanto a la construcción y funcionamiento de los vehículos.</p>
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autores/as</div>
  <div class="quarto-title-meta-heading">Afiliación</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://www.linkedin.com/in/jorgeborjas25/">Jorge Borja, Mag</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://uninorte.edu.co/">
            Universidad del Norte
            </a>
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://www.linkedin.com/in/jose-javier-mercado-reyes-246352214/">Jose Mercado, Mag</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="qué-haremos" class="level1">
<h1>¿Qué haremos?</h1>
<p>En esta sección, llevaremos a cabo un análisis exploratorio centrado en la tabla <code>constructors</code>, que abarca los datos de los equipos que han competido en las carreras disputadas desde 1950 hasta 2023. Sin embargo, para llevar a cabo este análisis de manera integral, necesitamos consolidar información proveniente de diversas fuentes. Utilizaremos consultas para unificar los datos de la tabla <code>constructors</code> con aquellos de las tablas <code>circuits</code> (que contiene información sobre los circuitos donde se celebran las carreras de Fórmula 1), <code>results</code> (que proporciona los resultados de las carreras), <code>pit_stops</code> (paradas realizadas en boxes).</p>
<p>Es fundamental destacar que, para la tabla <code>results</code> nos enfocaremos exclusivamente en los equipos que obtuvieron puntos en cada carrera. Asimismo, de la tabla <code>pit_stops</code>, extraeremos únicamente la información correspondiente a la parada en boxes más rápida realizada.</p>
</section>
<section id="librerías" class="level1">
<h1>Librerías</h1>
<p>Para este proyecto trabajaremos con las siguientes librerías:</p>
<ul>
<li>Pandas</li>
<li>Psycopg2</li>
<li>Plotly</li>
<li>Matplotlib</li>
<li>Seaborn</li>
<li>Scikit-learn</li>
</ul>
<p>Pueden instalarse utilizando el siguiente comando desde la terminal: <code>pip install pandas psycopg2 plotly...</code>, o bien, mediante el archivo <a href="https://github.com/unfresh25/f1-dashboard">requirements.txt</a> utilizando <code>pip install -r requirements.txt</code> en la terminal.</p>
<p>Una vez instaladas, podemos importarlas en nuestro entorno de trabajo de la siguiente manera:</p>
<div id="f5b9ffbc" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> psycopg2 <span class="im">as</span> psy</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> psycopg2 <span class="im">import</span> Error</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.experimental <span class="im">import</span> enable_iterative_imputer</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> IterativeImputer</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.graph_objects <span class="im">as</span> go</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'white'</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Además, haremos uso de la siguiente función para evitar la repetición de código y facilitar la conexión a la base de datos:</p>
<div id="9db9f24a" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> connection_db() <span class="op">-&gt;</span> psy.extensions.connection:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        conn <span class="op">=</span> psy.<span class="ex">connect</span>(DATABASE_URL)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> conn</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">'Error while connecting to PostgreSQL'</span>, e)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es importante destacar que en esta función, obtenemos una variable de entorno que almacena los datos de conexión a la base de datos. En este caso, estamos utilizando <a href="https://neon.tech/">Neon</a> que nos permite crear un servidor de bases de datos con <code>PostgreSQL</code>.</p>
</section>
<section id="obtención-de-los-datos" class="level1">
<h1>Obtención de los datos</h1>
<p>Veamos inicialmente las columnas que tenemos para cada una de las tablas mencionadas.</p>
<section id="tabla-constructors" class="level2">
<h2 class="anchored" data-anchor-id="tabla-constructors">Tabla constructors</h2>
<div id="c777f0a9" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT *</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM constructors</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="st">            LIMIT 5;</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    display(records_data)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">constructorid</th>
<th data-quarto-table-cell-role="th">constructorref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">nationality</th>
<th data-quarto-table-cell-role="th">url</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>http://en.wikipedia.org/wiki/McLaren</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>bmw_sauber</td>
<td>BMW Sauber</td>
<td>German</td>
<td>http://en.wikipedia.org/wiki/BMW_Sauber</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>williams</td>
<td>Williams</td>
<td>British</td>
<td>http://en.wikipedia.org/wiki/Williams_Grand_Pr...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>renault</td>
<td>Renault</td>
<td>French</td>
<td>http://en.wikipedia.org/wiki/Renault_in_Formul...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>toro_rosso</td>
<td>Toro Rosso</td>
<td>Italian</td>
<td>http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="tabla-circuits" class="level2">
<h2 class="anchored" data-anchor-id="tabla-circuits">Tabla circuits</h2>
<div id="8dfd21c0" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT *</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM circuits</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="st">            LIMIT 5;</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    display(records_data)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">circuitid</th>
<th data-quarto-table-cell-role="th">circuitref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">location</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">lng</th>
<th data-quarto-table-cell-role="th">alt</th>
<th data-quarto-table-cell-role="th">url</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>albert_park</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>-37.8497</td>
<td>144.968</td>
<td>10</td>
<td>http://en.wikipedia.org/wiki/Melbourne_Grand_P...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>sepang</td>
<td>Sepang International Circuit</td>
<td>Kuala Lumpur</td>
<td>Malaysia</td>
<td>2.76083</td>
<td>101.738</td>
<td>18</td>
<td>http://en.wikipedia.org/wiki/Sepang_Internatio...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>bahrain</td>
<td>Bahrain International Circuit</td>
<td>Sakhir</td>
<td>Bahrain</td>
<td>26.0325</td>
<td>50.5106</td>
<td>7</td>
<td>http://en.wikipedia.org/wiki/Bahrain_Internati...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>catalunya</td>
<td>Circuit de Barcelona-Catalunya</td>
<td>Montmeló</td>
<td>Spain</td>
<td>41.57</td>
<td>2.26111</td>
<td>109</td>
<td>http://en.wikipedia.org/wiki/Circuit_de_Barcel...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>istanbul</td>
<td>Istanbul Park</td>
<td>Istanbul</td>
<td>Turkey</td>
<td>40.9517</td>
<td>29.405</td>
<td>130</td>
<td>http://en.wikipedia.org/wiki/Istanbul_Park</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="tabla-results" class="level2">
<h2 class="anchored" data-anchor-id="tabla-results">Tabla results</h2>
<div id="61057674" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT *</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM results</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="st">            LIMIT 5;</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    display(records_data)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">resultid</th>
<th data-quarto-table-cell-role="th">raceid</th>
<th data-quarto-table-cell-role="th">driverid</th>
<th data-quarto-table-cell-role="th">constructorid</th>
<th data-quarto-table-cell-role="th">number</th>
<th data-quarto-table-cell-role="th">grid</th>
<th data-quarto-table-cell-role="th">position</th>
<th data-quarto-table-cell-role="th">positiontext</th>
<th data-quarto-table-cell-role="th">positionorder</th>
<th data-quarto-table-cell-role="th">points</th>
<th data-quarto-table-cell-role="th">laps</th>
<th data-quarto-table-cell-role="th">time</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
<th data-quarto-table-cell-role="th">fastestlap</th>
<th data-quarto-table-cell-role="th">rank</th>
<th data-quarto-table-cell-role="th">fastestlaptime</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">statusid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>18</td>
<td>1</td>
<td>1</td>
<td>22</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>10</td>
<td>58</td>
<td>1:34:50.616</td>
<td>5690616</td>
<td>39</td>
<td>2</td>
<td>1:27.452</td>
<td>218.300</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>18</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>5</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>8</td>
<td>58</td>
<td>+5.478</td>
<td>5696094</td>
<td>41</td>
<td>3</td>
<td>1:27.739</td>
<td>217.586</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>18</td>
<td>3</td>
<td>3</td>
<td>7</td>
<td>7</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>6</td>
<td>58</td>
<td>+8.163</td>
<td>5698779</td>
<td>41</td>
<td>5</td>
<td>1:28.090</td>
<td>216.719</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>18</td>
<td>4</td>
<td>4</td>
<td>5</td>
<td>11</td>
<td>4</td>
<td>4</td>
<td>4</td>
<td>5</td>
<td>58</td>
<td>+17.181</td>
<td>5707797</td>
<td>58</td>
<td>7</td>
<td>1:28.603</td>
<td>215.464</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>18</td>
<td>5</td>
<td>1</td>
<td>23</td>
<td>3</td>
<td>5</td>
<td>5</td>
<td>5</td>
<td>4</td>
<td>58</td>
<td>+18.014</td>
<td>5708630</td>
<td>43</td>
<td>1</td>
<td>1:27.418</td>
<td>218.385</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="tabla-pit-stops" class="level2">
<h2 class="anchored" data-anchor-id="tabla-pit-stops">Tabla pit stops</h2>
<div id="9471ce0a" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT *</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM pit_stops</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="st">            LIMIT 5;</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    display(records_data)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">raceid</th>
<th data-quarto-table-cell-role="th">driverid</th>
<th data-quarto-table-cell-role="th">stop</th>
<th data-quarto-table-cell-role="th">lap</th>
<th data-quarto-table-cell-role="th">time</th>
<th data-quarto-table-cell-role="th">duration</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>841</td>
<td>153</td>
<td>1</td>
<td>1</td>
<td>17:05:23</td>
<td>26.898</td>
<td>26898</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>841</td>
<td>30</td>
<td>1</td>
<td>1</td>
<td>17:05:52</td>
<td>25.021</td>
<td>25021</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>841</td>
<td>17</td>
<td>1</td>
<td>11</td>
<td>17:20:48</td>
<td>23.426</td>
<td>23426</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>841</td>
<td>4</td>
<td>1</td>
<td>12</td>
<td>17:22:34</td>
<td>23.251</td>
<td>23251</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>841</td>
<td>13</td>
<td>1</td>
<td>13</td>
<td>17:24:10</td>
<td>23.842</td>
<td>23842</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="tabla-final" class="level2">
<h2 class="anchored" data-anchor-id="tabla-final">Tabla final</h2>
<p>Con base en las columnas proporcionadas de cada tabla, podemos listar las que se utilizarán en el análisis de la siguiente manera:</p>
<ul>
<li><strong>constructors</strong>: constructorId, constructorRef, name, nationality</li>
<li><strong>Circuits</strong>: name, location, country.</li>
<li><strong>Results</strong>: raceId, driverId, points, grid, laps, milliseconds, fastestlap, rank, fastestlapspeed, number, status.</li>
<li><strong>Pit Stops</strong>: stop, miliseconds.</li>
</ul>
<p>Realicemos entonces la consulta a la base de datos para obtener esta tabla.</p>
<div id="58f37694" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    connection <span class="op">=</span> connection_db()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    cursor <span class="op">=</span> connection.cursor()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    cursor.execute(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="st">            SELECT </span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="st">                c.constructorid, c.constructorref, c.name, c.nationality,</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="st">                circuits.name AS circuit_name, circuits.location AS circuit_location, circuits.country AS circuit_country,</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="st">                races.year,</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="st">                r.raceid, r.driverid, r.number, r.grid, r.positionorder, r.points, r.laps, r.milliseconds, r.fastestlap, r.rank, r.fastestlapspeed, r.statusid,</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="st">                fastest_pit_stop.stop AS fastest_pit_stop, fastest_pit_stop.milliseconds AS fastest_pit_stop_time</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="st">            FROM constructors c</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN constructor_results ON c.constructorId = constructor_results.constructorId</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN races ON constructor_results.raceId = races.raceId</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN circuits ON races.circuitId = circuits.circuitId</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN (</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="st">                SELECT raceId, constructorId, MAX(points) AS points</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="st">                FROM constructor_standings</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="st">                GROUP BY raceId, constructorId</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="st">            ) AS cs ON constructor_results.raceId = cs.raceId AND constructor_results.constructorId = cs.constructorId</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="st">            JOIN results as r ON constructor_results.raceId = r.raceId AND constructor_results.constructorId = r.constructorId AND r.points &gt; 0</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="st">            LEFT JOIN (</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="st">                SELECT ps.raceId, ps.driverId, ps.stop, ps.milliseconds</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="st">                FROM pit_stops ps</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="st">                JOIN drivers d ON ps.driverId = d.driverId</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="st">                WHERE (ps.raceId, ps.driverId, ps.milliseconds) IN (</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="st">                    SELECT raceId, driverId, MIN(milliseconds)</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM pit_stops</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY raceId, driverId</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="st">                )</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="st">            ) AS fastest_pit_stop ON constructor_results.raceId = fastest_pit_stop.raceId AND r.driverId = fastest_pit_stop.driverId;</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> cursor.fetchall()</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    records_data <span class="op">=</span> pd.DataFrame(records)</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> []</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> cursor.description:</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        columns.append(column[<span class="dv">0</span>])</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    records_data.columns <span class="op">=</span> columns</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>    display(records_data.head())</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> (<span class="pp">Exception</span>, Error) <span class="im">as</span> e:</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Error while executing the query'</span>, e)</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a><span class="cf">finally</span>:</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(connection):</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>        cursor.close()</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>        connection.close()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">constructorid</th>
<th data-quarto-table-cell-role="th">constructorref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">nationality</th>
<th data-quarto-table-cell-role="th">circuit_name</th>
<th data-quarto-table-cell-role="th">circuit_location</th>
<th data-quarto-table-cell-role="th">circuit_country</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">raceid</th>
<th data-quarto-table-cell-role="th">driverid</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">positionorder</th>
<th data-quarto-table-cell-role="th">points</th>
<th data-quarto-table-cell-role="th">laps</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
<th data-quarto-table-cell-role="th">fastestlap</th>
<th data-quarto-table-cell-role="th">rank</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">statusid</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>1</td>
<td>...</td>
<td>1</td>
<td>10</td>
<td>58</td>
<td>5690616.0</td>
<td>39.0</td>
<td>2.0</td>
<td>218.300</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>bmw_sauber</td>
<td>BMW Sauber</td>
<td>German</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>2</td>
<td>...</td>
<td>2</td>
<td>8</td>
<td>58</td>
<td>5696094.0</td>
<td>41.0</td>
<td>3.0</td>
<td>217.586</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>williams</td>
<td>Williams</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>3</td>
<td>...</td>
<td>3</td>
<td>6</td>
<td>58</td>
<td>5698779.0</td>
<td>41.0</td>
<td>5.0</td>
<td>216.719</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>renault</td>
<td>Renault</td>
<td>French</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>4</td>
<td>...</td>
<td>4</td>
<td>5</td>
<td>58</td>
<td>5707797.0</td>
<td>58.0</td>
<td>7.0</td>
<td>215.464</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>5</td>
<td>...</td>
<td>5</td>
<td>4</td>
<td>58</td>
<td>5708630.0</td>
<td>43.0</td>
<td>1.0</td>
<td>218.385</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 22 columns</p>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-exploratorio-de-datos" class="level1">
<h1>Análisis exploratorio de datos</h1>
<p>En esta sección nos sumergiremos en la comprensión de los datos disponibles, exploraremos los tipos de variables presentes, calcularemos medidas de tendencia central, llevaremos a cabo la depuración de los datos y procederemos a su visualización.</p>
<p>Para llevar a cabo este análisis, nos apoyaremos en el marco de trabajo establecido, APP Framework.</p>
<ol type="1">
<li><strong>Atención</strong>: Entender el conjunto de datos.</li>
<li><strong>Propósito</strong>: Establecer objetivos claros.</li>
<li><strong>Proceso</strong>: Realizar el Análisis Exploratorio de Datos (EDA) propiamente dicho.</li>
<li><strong>Beneficio</strong>: Extraer y aplicar los resultados obtenidos.</li>
</ol>
<section id="conociendo-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="conociendo-los-datos">Conociendo los datos</h2>
<p>Conocer los datos es un paso fundamental en cualquier análisis. Proporciona una comprensión inicial del problema, permite validar la calidad de los datos, seleccionar características relevantes, preparar los datos adecuadamente y generar ideas y hipótesis. En resumen, la exploración inicial de los datos sienta las bases para un análisis más profundo y asegura que los resultados sean significativos y confiables.</p>
<section id="tipos-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="tipos-de-datos">Tipos de datos</h3>
<p>Para realizar un análisis exploratorio, primero debes conocer el tipo de variables con las que estamos tratando. Conocer si tenemos variables numéricas o categóricas podrían determinar el rumbo del análisis que realizaremos.</p>
<div id="fa36dde3" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>records_data.dtypes</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>constructorid              int64
constructorref            object
name                      object
nationality               object
circuit_name              object
circuit_location          object
circuit_country           object
year                       int64
raceid                     int64
driverid                   int64
number                     int64
grid                       int64
positionorder              int64
points                     int64
laps                       int64
milliseconds             float64
fastestlap               float64
rank                     float64
fastestlapspeed           object
statusid                   int64
fastest_pit_stop         float64
fastest_pit_stop_time    float64
dtype: object</code></pre>
</div>
</div>
<p>Observemos que todas las variables tienen el tipo de dato correcto, excepto la columna <code>fastestlapspeed</code>, que toma valores numéricos pero está siendo interpretada como un dato tipo <code>object</code>. Por lo tanto, es necesario convertir esta columna en tipo numérico. Además, vamos a cambiar los tipos de datos de las variables <code>raceid</code>, <code>statusid</code>,<code>circuitid</code>, <code>driverid</code> y <code>constructorid</code> a tipo <code>object</code>.</p>
<div id="2821529b" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>records_data[<span class="st">'fastestlapspeed'</span>] <span class="op">=</span> pd.to_numeric(records_data[<span class="st">'fastestlapspeed'</span>])</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>records_data[[<span class="st">'raceid'</span>, <span class="st">'driverid'</span>, <span class="st">'constructorid'</span>, <span class="st">'statusid'</span>]] <span class="op">=</span> records_data[[<span class="st">'raceid'</span>, <span class="st">'driverid'</span>, <span class="st">'constructorid'</span>, <span class="st">'statusid'</span>]].astype(<span class="st">'object'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>records_data.dtypes</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>constructorid             object
constructorref            object
name                      object
nationality               object
circuit_name              object
circuit_location          object
circuit_country           object
year                       int64
raceid                    object
driverid                  object
number                     int64
grid                       int64
positionorder              int64
points                     int64
laps                       int64
milliseconds             float64
fastestlap               float64
rank                     float64
fastestlapspeed          float64
statusid                  object
fastest_pit_stop         float64
fastest_pit_stop_time    float64
dtype: object</code></pre>
</div>
</div>
</section>
<section id="dimensiones-de-los-registros" class="level3">
<h3 class="anchored" data-anchor-id="dimensiones-de-los-registros">Dimensiones de los registros</h3>
<p>Determinar el tamaño de nuestros registros es fundamental, ya que nos permite comprender la magnitud de la información que estamos manejando. Esto a su vez nos ayuda a establecer posibles caminos a seguir en caso de realizar transformaciones y análisis adicionales.</p>
<div id="3238ee54" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>records_data.shape</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>(7441, 22)</code></pre>
</div>
</div>
<div id="e36c185e" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(records_data[<span class="st">'constructorref'</span>].unique())</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>88</code></pre>
</div>
</div>
<p>Esto indica que desde el año 1950 hasta el 2023, en las más de 1000 carreras que se han llevado a cabo, han competido 88 equipos en esta competencia. Además, teniendo más de 7000 registros significa que estamos trabajando con una cantidad considerable de datos sobre equipos constructores.</p>
</section>
<section id="datos-faltantes" class="level3">
<h3 class="anchored" data-anchor-id="datos-faltantes">Datos faltantes</h3>
<p>Determinar la presencia de datos faltantes es crucial, ya que puede indicar si podemos confiar en una columna para el análisis o si necesitamos tomar medidas para imputar esos valores ausentes.</p>
<div id="98e589c4" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>records_data.isnull().<span class="bu">sum</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>constructorid               0
constructorref              0
name                        0
nationality                 0
circuit_name                0
circuit_location            0
circuit_country             0
year                        0
raceid                      0
driverid                    0
number                      0
grid                        0
positionorder               0
points                      0
laps                        0
milliseconds             1546
fastestlap               3888
rank                     3877
fastestlapspeed          3888
statusid                    0
fastest_pit_stop         4932
fastest_pit_stop_time    4932
dtype: int64</code></pre>
</div>
</div>
<p>Con los resultados obtenidos, observamos que tenemos una cantidad significativa de datos faltantes. Esta situación puede afectar los análisis futuros, dependiendo del tipo de variable que estemos considerando. Es importante determinar un método adecuado para la imputación de datos en caso de que sea necesario. Veamos el porcentaje que representa esta cantidad de datos faltantes en el total de nuestros datos.</p>
<div id="1a2a6516" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>missing_values <span class="op">=</span> records_data.isnull().<span class="bu">sum</span>()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>missing_percentage <span class="op">=</span> <span class="bu">round</span>((missing_values <span class="op">/</span> <span class="bu">len</span>(records_data)) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">4</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>missing_percentage</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>constructorid             0.0000
constructorref            0.0000
name                      0.0000
nationality               0.0000
circuit_name              0.0000
circuit_location          0.0000
circuit_country           0.0000
year                      0.0000
raceid                    0.0000
driverid                  0.0000
number                    0.0000
grid                      0.0000
positionorder             0.0000
points                    0.0000
laps                      0.0000
milliseconds             20.7768
fastestlap               52.2510
rank                     52.1032
fastestlapspeed          52.2510
statusid                  0.0000
fastest_pit_stop         66.2814
fastest_pit_stop_time    66.2814
dtype: float64</code></pre>
</div>
</div>
<p>Tenemos un gran porcentaje de datos faltantes en nuestras variables. Sin embargo, estos datos faltantes parecen estar concentrados en las variables relacionadas con medidas de tiempos y velocidades. Esto sugiere que estos datos podrían faltar debido a limitaciones técnicas o falta de registro en las fechas más antiguas, donde la toma de estas medidas podría no haber sido sistemática.</p>
<p>Para comprender mejor la distribución de estos datos faltantes, examinemos en qué fechas están ocurriendo y verifiquemos la fecha máxima y mínima en la que faltan estas observaciones.</p>
<div id="0d64f565" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>records_data[records_data.isnull().<span class="bu">any</span>(axis <span class="op">=</span> <span class="dv">1</span>)]</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">constructorid</th>
<th data-quarto-table-cell-role="th">constructorref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">nationality</th>
<th data-quarto-table-cell-role="th">circuit_name</th>
<th data-quarto-table-cell-role="th">circuit_location</th>
<th data-quarto-table-cell-role="th">circuit_country</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">raceid</th>
<th data-quarto-table-cell-role="th">driverid</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">positionorder</th>
<th data-quarto-table-cell-role="th">points</th>
<th data-quarto-table-cell-role="th">laps</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
<th data-quarto-table-cell-role="th">fastestlap</th>
<th data-quarto-table-cell-role="th">rank</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">statusid</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>1</td>
<td>...</td>
<td>1</td>
<td>10</td>
<td>58</td>
<td>5690616.0</td>
<td>39.0</td>
<td>2.0</td>
<td>218.300</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>bmw_sauber</td>
<td>BMW Sauber</td>
<td>German</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>2</td>
<td>...</td>
<td>2</td>
<td>8</td>
<td>58</td>
<td>5696094.0</td>
<td>41.0</td>
<td>3.0</td>
<td>217.586</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>williams</td>
<td>Williams</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>3</td>
<td>...</td>
<td>3</td>
<td>6</td>
<td>58</td>
<td>5698779.0</td>
<td>41.0</td>
<td>5.0</td>
<td>216.719</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>renault</td>
<td>Renault</td>
<td>French</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>4</td>
<td>...</td>
<td>4</td>
<td>5</td>
<td>58</td>
<td>5707797.0</td>
<td>58.0</td>
<td>7.0</td>
<td>215.464</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Albert Park Grand Prix Circuit</td>
<td>Melbourne</td>
<td>Australia</td>
<td>2008</td>
<td>18</td>
<td>5</td>
<td>...</td>
<td>5</td>
<td>4</td>
<td>58</td>
<td>5708630.0</td>
<td>43.0</td>
<td>1.0</td>
<td>218.385</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7299</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Autódromo Hermanos Rodríguez</td>
<td>Mexico City</td>
<td>Mexico</td>
<td>2022</td>
<td>1094</td>
<td>846</td>
<td>...</td>
<td>9</td>
<td>2</td>
<td>70</td>
<td>NaN</td>
<td>48.0</td>
<td>17.0</td>
<td>185.779</td>
<td>11</td>
<td>1.0</td>
<td>22585.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7300</td>
<td>51</td>
<td>alfa</td>
<td>Alfa Romeo</td>
<td>Swiss</td>
<td>Autódromo Hermanos Rodríguez</td>
<td>Mexico City</td>
<td>Mexico</td>
<td>2022</td>
<td>1094</td>
<td>822</td>
<td>...</td>
<td>10</td>
<td>1</td>
<td>70</td>
<td>NaN</td>
<td>43.0</td>
<td>16.0</td>
<td>185.866</td>
<td>11</td>
<td>1.0</td>
<td>23863.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7379</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Circuit de Monaco</td>
<td>Monte-Carlo</td>
<td>Monaco</td>
<td>2023</td>
<td>1104</td>
<td>846</td>
<td>...</td>
<td>9</td>
<td>2</td>
<td>77</td>
<td>NaN</td>
<td>46.0</td>
<td>19.0</td>
<td>154.324</td>
<td>11</td>
<td>1.0</td>
<td>24663.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7380</td>
<td>1</td>
<td>mclaren</td>
<td>McLaren</td>
<td>British</td>
<td>Circuit de Monaco</td>
<td>Monte-Carlo</td>
<td>Monaco</td>
<td>2023</td>
<td>1104</td>
<td>857</td>
<td>...</td>
<td>10</td>
<td>1</td>
<td>77</td>
<td>NaN</td>
<td>47.0</td>
<td>14.0</td>
<td>154.983</td>
<td>11</td>
<td>1.0</td>
<td>25851.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7430</td>
<td>117</td>
<td>aston_martin</td>
<td>Aston Martin</td>
<td>British</td>
<td>Hungaroring</td>
<td>Budapest</td>
<td>Hungary</td>
<td>2023</td>
<td>1109</td>
<td>840</td>
<td>...</td>
<td>10</td>
<td>1</td>
<td>69</td>
<td>NaN</td>
<td>54.0</td>
<td>11.0</td>
<td>189.051</td>
<td>11</td>
<td>1.0</td>
<td>21910.0</td>
</tr>
</tbody>
</table>

<p>5280 rows × 22 columns</p>
</div>
</div>
</div>
</div>
<div id="0e341766" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>Fecha mínima:  1958
Fecha promedio:  1990
Fecha máxima:  2023</code></pre>
</div>
</div>
<p>Observando estos resultados, podemos confirmar nuestra teoría. Estos registros faltantes pueden ser debidos a limitaciones técnicas en aquellos tiempos. Sin embargo, también tenemos datos faltantes recientes.</p>
</section>
</section>
<section id="exploración-de-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="exploración-de-los-datos">Exploración de los datos</h2>
<p>En esta sección realizaremos el verdadero análisis exploratorio de nuestros datos. Abordaremos los siguientes aspectos:</p>
<ol type="1">
<li><p><strong>Medidas de tendencia central</strong>: Calcularemos medidas como la media, la mediana y la moda para entender mejor la distribución de nuestros datos.</p></li>
<li><p><strong>Limpieza de los datos</strong>: Abordaremos la limpieza de nuestros datos, incluyendo la búsqueda de datos atípicos.</p></li>
<li><p><strong>Transformación</strong>: Determinaremos si es necesario aplicar alguna transformación a nuestros datos para facilitar los análisis subsiguientes.</p></li>
<li><p><strong>Visualización</strong>: Utilizaremos herramientas gráficas para explorar el comportamiento de nuestros datos y extraer patrones o tendencias.</p></li>
</ol>
<p>Esta fase nos permitirá comprender mejor la naturaleza de nuestros datos y prepararlos adecuadamente para análisis más avanzados.</p>
<section id="medidas-de-tendencia-central" class="level3">
<h3 class="anchored" data-anchor-id="medidas-de-tendencia-central">Medidas de tendencia central</h3>
<div id="d4ef56d7" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>records_data.describe()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">number</th>
<th data-quarto-table-cell-role="th">grid</th>
<th data-quarto-table-cell-role="th">positionorder</th>
<th data-quarto-table-cell-role="th">points</th>
<th data-quarto-table-cell-role="th">laps</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
<th data-quarto-table-cell-role="th">fastestlap</th>
<th data-quarto-table-cell-role="th">rank</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>5.895000e+03</td>
<td>3553.000000</td>
<td>3564.000000</td>
<td>3553.000000</td>
<td>2509.000000</td>
<td>2.509000e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1997.963177</td>
<td>14.495498</td>
<td>7.137078</td>
<td>4.354522</td>
<td>6.467679</td>
<td>62.388792</td>
<td>5.989774e+06</td>
<td>46.603152</td>
<td>6.680415</td>
<td>206.006290</td>
<td>1.536070</td>
<td>3.173199e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>18.309481</td>
<td>15.192749</td>
<td>4.989723</td>
<td>2.463845</td>
<td>5.667732</td>
<td>13.737097</td>
<td>1.089727e+06</td>
<td>14.355980</td>
<td>4.232408</td>
<td>20.582848</td>
<td>0.761929</td>
<td>9.771809e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1958.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>2.070710e+05</td>
<td>2.000000</td>
<td>0.000000</td>
<td>147.980000</td>
<td>1.000000</td>
<td>1.317300e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1983.000000</td>
<td>5.000000</td>
<td>3.000000</td>
<td>2.000000</td>
<td>2.000000</td>
<td>54.000000</td>
<td>5.388156e+06</td>
<td>39.000000</td>
<td>3.000000</td>
<td>195.557000</td>
<td>1.000000</td>
<td>2.147400e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>2002.000000</td>
<td>10.000000</td>
<td>6.000000</td>
<td>4.000000</td>
<td>4.000000</td>
<td>61.000000</td>
<td>5.771321e+06</td>
<td>48.000000</td>
<td>6.000000</td>
<td>206.603000</td>
<td>1.000000</td>
<td>2.287400e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>2014.000000</td>
<td>19.000000</td>
<td>10.000000</td>
<td>6.000000</td>
<td>9.000000</td>
<td>71.000000</td>
<td>6.295221e+06</td>
<td>56.000000</td>
<td>10.000000</td>
<td>219.005000</td>
<td>2.000000</td>
<td>2.463900e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2023.000000</td>
<td>99.000000</td>
<td>26.000000</td>
<td>21.000000</td>
<td>50.000000</td>
<td>110.000000</td>
<td>1.472659e+07</td>
<td>85.000000</td>
<td>20.000000</td>
<td>257.320000</td>
<td>6.000000</td>
<td>1.517308e+06</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p><br></p>
<p>Estos resultados nos pueden permitir concluir lo siguiente:</p>
<ul>
<li><p><strong>Puntos, posición en la parrilla y número de vueltas</strong>: Los datos muestran que el promedio de puntos obtenidos por carrera es de aproximadamente 6.47. La posición promedio en la parrilla de salida es alrededor de 7.14. En cuanto al número de vueltas, el promedio es de aproximadamente 62.39. Estas variabilidades indican que hay una amplia gama de resultados en términos de puntos, posición en la parrilla y número de vueltas, lo que podría atribuirse a diferencias en la dificultad de los circuitos, la calidad de los vehículos y las estrategias de los equipos en cada carrera.</p></li>
<li><p><strong>Tiempo de carrera y velocidad</strong>: El tiempo medio de carrera es de aproximadamente 5.99 millones de milisegundos (alrededor de 99.83 minutos) millones de milisegundos. Esta variabilidad en los tiempos de carrera puede deberse a la longitud del circuito, las condiciones climáticas y la cantidad de incidentes en la pista. La velocidad media de la vuelta más rápida realizada por el ganador es de alrededor de 206.01 km/h. Estas diferencias en la velocidad pueden ser atribuibles a las características específicas del circuito y la competencia entre los conductores.</p></li>
<li><p><strong>Paradas en boxes</strong>: El tiempo medio para la parada en boxes más rápida es de aproximadamente 31.73 segundos. Las paradas en boxes indican que hay una variabilidad en los tiempos de pit stop entre las carreras, que puede estar influenciada por factores como la estrategia del equipo y la eficiencia en el box.</p></li>
</ul>
</section>
<section id="limpieza-de-los-datos" class="level3">
<h3 class="anchored" data-anchor-id="limpieza-de-los-datos">Limpieza de los datos</h3>
<p>La limpieza de datos es una etapa crucial en cualquier análisis, por lo que en este apartado trataremos los datos faltantes y observaremos si existen datos atípicos en nuestras variables.</p>
<section id="datos-faltantes-1" class="level4">
<h4 class="anchored" data-anchor-id="datos-faltantes-1">Datos faltantes</h4>
<p>Existen diversas estrategias para abordar este problema. Usualmente, en este tipo de análisis se recurre a la <code>imputación</code> de valores faltantes utilizando la <code>media</code>, <code>moda</code> o <code>mediana</code>, o llenando los datos con los valores <code>anteriores o siguientes</code>. Sin embargo, estas técnicas pueden no ser óptimas para conjuntos de datos extensos o con características específicas.</p>
<p>En nuestro caso, una estrategia efectiva sería utilizar la <code>imputación</code> de datos faltantes basada en puntos similares en los datos mediante el algoritmo <code>KNN (K-Nearest Neighbors)</code> y <code>Random Forest Classification</code>. Este método considera las características de observaciones similares para estimar los valores faltantes de manera más precisa y realista, lo que resulta especialmente útil en conjuntos de datos complejos como el nuestro.</p>
<p>Inicialmente, creemos un <code>DataFrame</code> temporal donde estarán los mismos datos de <code>records_data</code> pero sin las columnas correspondientes a tipo <code>object</code>.</p>
<div id="fb6a29fb" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>temp_df <span class="op">=</span> records_data.select_dtypes(exclude<span class="op">=</span>[<span class="st">'object'</span>])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>imputer <span class="op">=</span> IterativeImputer(min_value<span class="op">=</span><span class="dv">0</span>, max_iter<span class="op">=</span><span class="dv">30</span>, imputation_order<span class="op">=</span><span class="st">'roman'</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>imputed_data <span class="op">=</span> imputer.fit_transform(temp_df)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>temp_df_imputed <span class="op">=</span> pd.DataFrame(imputed_data, columns<span class="op">=</span>temp_df.columns)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>temp_df_imputed.isnull().<span class="bu">sum</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>year                     0
number                   0
grid                     0
positionorder            0
points                   0
laps                     0
milliseconds             0
fastestlap               0
rank                     0
fastestlapspeed          0
fastest_pit_stop         0
fastest_pit_stop_time    0
dtype: int64</code></pre>
</div>
</div>
<p>Bien, ya no tenemos datos faltantes. Ahora, verifiquemos si los resultados obtenidos en las medidas de tendencia central del DataFrame original cambiaron significativamente.</p>
<div id="50a1e469" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>temp_df_imputed.describe()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">number</th>
<th data-quarto-table-cell-role="th">grid</th>
<th data-quarto-table-cell-role="th">positionorder</th>
<th data-quarto-table-cell-role="th">points</th>
<th data-quarto-table-cell-role="th">laps</th>
<th data-quarto-table-cell-role="th">milliseconds</th>
<th data-quarto-table-cell-role="th">fastestlap</th>
<th data-quarto-table-cell-role="th">rank</th>
<th data-quarto-table-cell-role="th">fastestlapspeed</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop</th>
<th data-quarto-table-cell-role="th">fastest_pit_stop_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7.441000e+03</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7441.000000</td>
<td>7.441000e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1997.963177</td>
<td>14.495498</td>
<td>7.137078</td>
<td>4.354522</td>
<td>6.467679</td>
<td>62.388792</td>
<td>6.081225e+06</td>
<td>37.759931</td>
<td>5.846977</td>
<td>196.131523</td>
<td>2.240600</td>
<td>3.454560e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>18.309481</td>
<td>15.192749</td>
<td>4.989723</td>
<td>2.463845</td>
<td>5.667732</td>
<td>13.737097</td>
<td>1.042933e+06</td>
<td>15.428452</td>
<td>3.313179</td>
<td>24.840240</td>
<td>0.824293</td>
<td>5.900247e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1958.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>2.070710e+05</td>
<td>0.000000</td>
<td>0.000000</td>
<td>102.884413</td>
<td>0.646780</td>
<td>0.000000e+00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1983.000000</td>
<td>5.000000</td>
<td>3.000000</td>
<td>2.000000</td>
<td>2.000000</td>
<td>54.000000</td>
<td>5.471968e+06</td>
<td>28.193697</td>
<td>3.334282</td>
<td>181.618486</td>
<td>1.843325</td>
<td>2.172100e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>2002.000000</td>
<td>10.000000</td>
<td>6.000000</td>
<td>4.000000</td>
<td>4.000000</td>
<td>61.000000</td>
<td>5.899051e+06</td>
<td>37.728190</td>
<td>5.300952</td>
<td>198.225000</td>
<td>2.185505</td>
<td>2.571253e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>2014.000000</td>
<td>19.000000</td>
<td>10.000000</td>
<td>6.000000</td>
<td>9.000000</td>
<td>71.000000</td>
<td>6.496058e+06</td>
<td>48.000000</td>
<td>7.430359</td>
<td>212.063000</td>
<td>2.871513</td>
<td>3.848875e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2023.000000</td>
<td>99.000000</td>
<td>26.000000</td>
<td>21.000000</td>
<td>50.000000</td>
<td>110.000000</td>
<td>1.472659e+07</td>
<td>85.000000</td>
<td>20.818095</td>
<td>327.756546</td>
<td>6.000000</td>
<td>1.517308e+06</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p><br></p>
<p>Comparando los resultados de las medidas de tendencia central antes y después de la imputación de datos con el algoritmo <code>KNN</code>, observamos algunas diferencias significativas en ciertas variables:</p>
<ul>
<li><p><strong>Puntos, posición en la parrilla y número de vueltas</strong>: No se observan cambios significativos en las medidas de tendencia central y dispersión de los puntos obtenidos, la posición en la parrilla de salida y el número de vueltas antes y después de la imputación de datos.</p></li>
<li><p><strong>Tiempo de carrera y velocidad</strong>: Después de la imputación de datos, se observa un ligero aumento en la media del tiempo de carrera, mientras que la desviación estándar disminuye. Esto sugiere una mayor consistencia en los tiempos de carrera entre las carreras. Por otro lado, no hay cambios significativos en las estadísticas de velocidad de la vuelta más rápida antes y después de la imputación.</p></li>
<li><p><strong>Paradas en boxes</strong>: Después de la imputación de datos, se observa un aumento en la media del tiempo de la parada más rápida, lo que indica que las paradas en boxes pueden haber sido ligeramente más lentas en promedio después de la imputación. Sin embargo, la desviación estándar disminuye, lo que sugiere una mayor consistencia en los tiempos de parada más rápida entre las carreras.</p></li>
</ul>
<p>Ahora que hemos realizado la imputación de datos, pasemos estos datos a nuestro dataframe original.</p>
<div id="7ed84b6a" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>records_data[temp_df.columns] <span class="op">=</span> temp_df_imputed</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>records_data.isnull().<span class="bu">sum</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>constructorid            0
constructorref           0
name                     0
nationality              0
circuit_name             0
circuit_location         0
circuit_country          0
year                     0
raceid                   0
driverid                 0
number                   0
grid                     0
positionorder            0
points                   0
laps                     0
milliseconds             0
fastestlap               0
rank                     0
fastestlapspeed          0
statusid                 0
fastest_pit_stop         0
fastest_pit_stop_time    0
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="datos-atípicos" class="level4">
<h4 class="anchored" data-anchor-id="datos-atípicos">Datos atípicos</h4>
<p>Veamos ahora si existen <code>datos atípicos</code> en nuestro registro. En este caso, utilizaremos el <code>rango intercuartílico (IQR)</code> para identificar los valores atípicos. Si un valor cae por debajo de <code>Q1 - 1.5 * IQR</code> o por encima de <code>Q3 + 1.5 * IQR</code>, se considera un valor atípico.</p>
<div id="7974b608" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>numeric_columns <span class="op">=</span> temp_df.columns</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> numeric_columns:</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    q1 <span class="op">=</span> records_data[col].quantile(<span class="fl">0.25</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    q3 <span class="op">=</span> records_data[col].quantile(<span class="fl">0.75</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    iqr <span class="op">=</span> q3 <span class="op">-</span> q1</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    lower_bound <span class="op">=</span> q1 <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    upper_bound <span class="op">=</span> q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    outliers <span class="op">=</span> records_data[(records_data[col] <span class="op">&lt;</span> lower_bound) <span class="op">|</span> (records_data[col] <span class="op">&gt;</span> upper_bound)]</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    n_outliers <span class="op">=</span> <span class="bu">len</span>(outliers)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'#Outliers in </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss"> are </span><span class="sc">{</span>n_outliers<span class="sc">}</span><span class="ss"> and represent a </span><span class="sc">{</span><span class="bu">round</span>(n_outliers<span class="op">/</span><span class="bu">len</span>(records_data) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">4</span>)<span class="sc">}</span><span class="ss">% of total records'</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#Outliers in year are 0 and represent a 0.0% of total records
#Outliers in number are 503 and represent a 6.7598% of total records
#Outliers in grid are 94 and represent a 1.2633% of total records
#Outliers in positionorder are 1 and represent a 0.0134% of total records
#Outliers in points are 274 and represent a 3.6823% of total records
#Outliers in laps are 263 and represent a 3.5345% of total records
#Outliers in milliseconds are 309 and represent a 4.1527% of total records
#Outliers in fastestlap are 10 and represent a 0.1344% of total records
#Outliers in rank are 272 and represent a 3.6554% of total records
#Outliers in fastestlapspeed are 155 and represent a 2.0831% of total records
#Outliers in fastest_pit_stop are 12 and represent a 0.1613% of total records
#Outliers in fastest_pit_stop_time are 451 and represent a 6.061% of total records</code></pre>
</div>
</div>
<p>Como podemos observar, respecto a los más de 7000 registros que tiene la tabla, hay una pequeña cantidada de datos significativa de datos atípicos en nuestras variables. Veamos gráficamente qué es lo que está ocurriendo con ellos.</p>
<p>Realizaremos un gráfico de <code>caja y bigotes</code> e <code>histogramas</code> para ver el comportamiento y la distribución de nuestros datos.</p>
<div id="19dcc08d" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>,<span class="dv">12</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> numeric_columns:</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">5</span>,<span class="dv">3</span>,i)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    plt.boxplot(records_data[col],whis<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-23-output-1.png" width="728" height="764" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="af499d70" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">12</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> numeric_columns:</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">5</span>, <span class="dv">3</span>, i)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    sns.histplot(records_data[col], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-24-output-1.png" width="758" height="945" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Dada la naturaleza de las variables, en algunos casos como <code>rank</code>, <code>lap</code>, <code>grid</code>, <code>points</code>, entre otros que son datos numéricos <code>discretos</code> y representan una <code>categoría</code> específica, es normal que existan datos atípicos. Por otro lado, para las otras variables en nuestra base de datos, estos datos atípicos no están afectando mucho la distribución de cada una de ellas, por lo tanto, no realizaremos cambios en ellas.</p>
</section>
</section>
</section>
<section id="visualización" class="level2">
<h2 class="anchored" data-anchor-id="visualización">Visualización</h2>
<p>La visualización es uno de los puntos más importantes a la hora de realizar una exploración de los datos. Con ella, no solo podemos encontrar las relaciones que existen entre nuestras variables, sino que también podemos representar gráficamente las informaciones más relevantes de los datos.</p>
<p>Comencemos visualizando los gráficos de <code>correlación</code> y <code>dispersión</code> entre las variables para comprender mejor sus relaciones y encontrar posibles patrones.</p>
<section id="gráfico-de-correlación" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-de-correlación">Gráfico de correlación</h3>
<div id="e54c53b0" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> records_data[numeric_columns].corr()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(corr, dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'PRGn'</span>, square<span class="op">=</span><span class="va">True</span>, center<span class="op">=</span><span class="dv">0</span>, mask<span class="op">=</span>mask)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-25-output-1.png" width="604" height="524" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos observar, las variables con una alta correlación (<code>&gt;0.5</code> o <code>&lt;-0.5</code>) son aquellas que están relacionadas entre sí, como <code>laps</code>, <code>fastestlapspeed</code>, <code>fastest_lap</code>, <code>positionorder</code>, <code>year</code>, <code>fastest_pip_stop</code> entre otras. Por lo tanto, esto no debería ser un problema y podemos proseguir con la exploración de los datos.</p>
</section>
<section id="gráfico-de-dispersión" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-de-dispersión">Gráfico de dispersión</h3>
<div id="33825751" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">12</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sns.pairplot(records_data[numeric_columns])</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 768x1152 with 0 Axes&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-26-output-2.png" width="2828" height="2828" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>De este gráfico podemos notar que a medida que pasan los años, los equipos han ha evolucionado progresivamente en términos de velocidades y tiempos de carreras obtenidos. La velocidad y duración en boxes han aumentado, lo que indica una mejora en los automóviles y las técnicas de revisión de ellos. Sin embargo, estos cambios en las velocidades y tiempos también se han vuelto más dispersos a lo largo de los años, lo que implica que ha habido una gran diferencia entre los equipos constructores. Además, también podemos observar algunas relaciones proporcionales en nuestras variables, como aquellas relacionadas nuevamente con las velocidades y tiempos.</p>
</section>
<section id="distribución-de-carreras" class="level3">
<h3 class="anchored" data-anchor-id="distribución-de-carreras">Distribución de carreras</h3>
<div id="bf3c817f" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> records_data.groupby(<span class="st">'name'</span>).size().reset_index(name<span class="op">=</span><span class="st">'total_races'</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.sort_values(by<span class="op">=</span><span class="st">'total_races'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.rename(columns<span class="op">=</span>{<span class="st">'name'</span>: <span class="st">'constructor_name'</span>})</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>top_constructors <span class="op">=</span> constructor_stats.head(<span class="dv">5</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>sns.histplot(constructor_stats[<span class="st">'total_races'</span>], kde<span class="op">=</span><span class="va">False</span>, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'skyblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribución del Número Total de Carreras por Constructor'</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Número Total de Carreras'</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frecuencia'</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> <span class="st">'</span><span class="ch">\n</span><span class="st">'</span>.join([<span class="ss">f"</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">. </span><span class="sc">{</span>row[<span class="st">'constructor_name'</span>]<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>row[<span class="st">'total_races'</span>]<span class="sc">}</span><span class="ss"> carreras"</span> <span class="cf">for</span> i, (index, row) <span class="kw">in</span> <span class="bu">enumerate</span>(top_constructors.iterrows(), start<span class="op">=</span><span class="dv">0</span>)])</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>plt.text(<span class="bu">max</span>(top_constructors[<span class="st">'total_races'</span>]) <span class="op">*</span> <span class="fl">1.02</span>, plt.ylim()[<span class="dv">1</span>] <span class="op">*</span> <span class="fl">0.9</span>, text, ha<span class="op">=</span><span class="st">'right'</span>, va<span class="op">=</span><span class="st">'top'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-27-output-1.png" width="758" height="662" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Se observa que la mayoría de los constructores han participado en una cantidad menor de carreras, con una concentración significativa cerca del cero. Esto indica que hay muchos equipos que han tenido una presencia breve en el deporte (pocas temporadas). Sin embargo, hay un pequeño grupo de equipos, como Ferrari y McLaren, que resaltan con una participación en un número mucho mayor de carreras, superando los 800 Grandes Premios, lo que subraya su posición como pilares históricos de la Fórmula 1 con una larga tradición de competencia continua.</p>
</section>
<section id="distribución-de-costructores-por-nacionalidad" class="level3">
<h3 class="anchored" data-anchor-id="distribución-de-costructores-por-nacionalidad">Distribución de costructores por nacionalidad</h3>
<div id="4374364d" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> records_data.groupby(<span class="st">'nationality'</span>).size().reset_index(name<span class="op">=</span><span class="st">'num_constructors'</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.sort_values(by<span class="op">=</span><span class="st">'num_constructors'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.rename(columns<span class="op">=</span>{<span class="st">'nationality'</span>: <span class="st">'constructor_nationality'</span>})</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>top_constructors <span class="op">=</span> constructor_stats.head(<span class="dv">5</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>))</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>constructor_stats.set_index(<span class="st">'constructor_nationality'</span>)[<span class="st">'num_constructors'</span>].plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Número de Constructores por Nacionalidad'</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Nacionalidad'</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Número de Constructores'</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)  </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout() </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-28-output-1.png" width="757" height="662" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>El gráfico muestra la distribución de constructores de Fórmula 1 por nacionalidad. La nacionalidad británica domina claramente con la mayor cantidad de constructores, lo cual resalta la influencia y la historia del Reino Unido en el automovilismo de F1. Le siguen con menor frecuencia los constructores americanos e italianos, reflejando también su papel significativo en la F1.</p>
<p>La presencia de una variedad de otras nacionalidades indica la diversidad internacional de los equipos, aunque con una representación mucho menor comparada con las tres principales. Esta distribución no solo refleja la historia y geografía del deporte sino también las industrias automotrices nacionales y su apoyo al automovilismo.</p>
</section>
<section id="top-5-equipos-más-ganadores" class="level3">
<h3 class="anchored" data-anchor-id="top-5-equipos-más-ganadores">Top 5 equipos más ganadores</h3>
<div id="e0dd5879" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> records_data[records_data[<span class="st">'positionorder'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> records_data.groupby(<span class="st">'name'</span>).size().reset_index(name<span class="op">=</span><span class="st">'total_wins'</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.sort_values(by<span class="op">=</span><span class="st">'total_wins'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>constructor_stats <span class="op">=</span> constructor_stats.rename(columns<span class="op">=</span>{<span class="st">'name'</span>: <span class="st">'constructor_name'</span>})</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>top_constructors <span class="op">=</span> constructor_stats.head(<span class="dv">5</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>))</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.bar(top_constructors[<span class="st">'constructor_name'</span>], top_constructors[<span class="st">'total_wins'</span>], color<span class="op">=</span><span class="st">'skyblue'</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Top 5 Equipos Más Ganadores en F1'</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Equipo'</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Número Total de Victorias'</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>plt.xticks()</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-29-output-1.png" width="671" height="595" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>El gráfico muestra el top 10 de equipos más ganadores en la historia de la Fórmula 1. Ferrari lidera con una diferencia significativa, destacando su legado como la escudería más exitosa. McLaren le sigue, con Mercedes, Williams y Red Bull completando los cinco primeros lugares. Estos equipos han sido fundamentales en el deporte, no solo por su número de victorias sino también por su influencia en la evolución de la competición.</p>
</section>
<section id="evolución-de-la-velocidad" class="level3">
<h3 class="anchored" data-anchor-id="evolución-de-la-velocidad">Evolución de la velocidad</h3>
<div id="2f2146a4" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sns.lineplot(x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'fastestlapspeed'</span>, data<span class="op">=</span>records_data, label<span class="op">=</span><span class="st">'Velocidad de Vuelta Más Rápida'</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Evolución de la velocidad a lo largo de los años'</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Año'</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Velocidad (km/h)'</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-30-output-1.png" width="663" height="669" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>El gráfico presenta la evolución de la velocidad de la vuelta más rápida en la Fórmula 1 a lo largo de los años. Se observan fluctuaciones en la velocidad a lo largo del tiempo, con una tendencia general al aumento. La sombra alrededor de la línea indica la variabilidad en la velocidad de la vuelta más rápida cada año, sugiriendo que, aunque hay años con velocidades pico, también existen otros factores que pueden afectar la velocidad, como las regulaciones técnicas, las condiciones meteorológicas o el diseño de los circuitos.</p>
<p>El incremento significativo de la velocidad podría atribuirse a avances tecnológicos en los motores y la aerodinámica, así como a cambios en las regulaciones de la F1 que permiten vehículos más rápidos. Sin embargo, el pico en los años recientes también puede reflejar el desarrollo y perfeccionamiento constante en las estrategias de carrera y la optimización del rendimiento del vehículo.</p>
</section>
<section id="evolución-de-la-velocidad-máxima-alcanzada-por-equipo" class="level3">
<h3 class="anchored" data-anchor-id="evolución-de-la-velocidad-máxima-alcanzada-por-equipo">Evolución de la velocidad máxima alcanzada por equipo</h3>
<div id="1bfed730" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, team <span class="kw">in</span> <span class="bu">zip</span>(axes.flatten(), top_constructors[<span class="st">'constructor_name'</span>]):</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    team_data <span class="op">=</span> records_data[records_data[<span class="st">'name'</span>] <span class="op">==</span> team]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    sns.lineplot(x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'fastestlapspeed'</span>, data<span class="op">=</span>team_data, ax<span class="op">=</span>ax)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Evolución de </span><span class="sc">{</span>team<span class="sc">}</span><span class="ss"> - Velocidad máxima alcanzada'</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Año'</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Velocidad máxima alcanzada (km/h)'</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-31-output-1.png" width="1142" height="758" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>La <strong>evolución de la velocidad máxima</strong> en la Fórmula 1 a lo largo de los años es un resultado complejo de factores como la tecnología, las regulaciones, el diseño de los circuitos y la competencia entre equipos. Cada equipo tiene su propia trayectoria, y las mejoras constantes o altibajos pueden atribuirse a diversas razones.</p>
</section>
<section id="evolución-de-las-paradas-en-boxes" class="level3">
<h3 class="anchored" data-anchor-id="evolución-de-las-paradas-en-boxes">Evolución de las paradas en boxes</h3>
<div id="688eb914" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>records_data[<span class="st">'fastest_pit_stop_time_in_seconds'</span>] <span class="op">=</span> records_data[<span class="st">'fastest_pit_stop_time'</span>] <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>sns.lineplot(x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'fastestlapspeed'</span>, data<span class="op">=</span>records_data, label<span class="op">=</span><span class="st">'Velocidad de Vuelta Más Rápida'</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Evolución de la velocidad a lo largo de los años'</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Año'</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Velocidad (km/h)'</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-32-output-1.png" width="663" height="669" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="evolución-de-las-paradas-en-boxes-por-equipo" class="level3">
<h3 class="anchored" data-anchor-id="evolución-de-las-paradas-en-boxes-por-equipo">Evolución de las paradas en boxes por equipo</h3>
<div id="81052b01" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">12</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, team <span class="kw">in</span> <span class="bu">zip</span>(axes.flatten(), top_constructors[<span class="st">'constructor_name'</span>]):</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    team_data <span class="op">=</span> records_data[records_data[<span class="st">'name'</span>] <span class="op">==</span> team]</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    sns.lineplot(x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'fastest_pit_stop_time_in_seconds'</span>, data<span class="op">=</span>team_data, ax<span class="op">=</span>ax)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Evolución de </span><span class="sc">{</span>team<span class="sc">}</span><span class="ss"> - Tiempo Promedio de Parada en Boxes'</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Año'</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Tiempo Promedio de Parada en Boxes (segundos)'</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="constructors_files/figure-html/cell-33-output-1.png" width="1142" height="1142" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>La gráfica muestra cómo ha evolucionado el tiempo promedio de parada en boxes para los mejores equipos de Fórmula 1 a lo largo de los años. Las mejoras tecnológicas, el entrenamiento del personal, las estrategias de carrera y los cambios en el diseño de los autos han influido en estos tiempos. Los equipos más eficientes han logrado reducir sus tiempos de parada, demostrando habilidad y dedicación en las carreras.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./races.html" class="pagination-link" aria-label="Análisis de la tabla races">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Análisis de la tabla races</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./drivers.html" class="pagination-link" aria-label="Análisis de la tabla drivers">
        <span class="nav-page-text">Análisis de la tabla drivers</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>